#!/usr/bin/env node
/**
 * Last Light setup wizard — `npx lastlight setup`
 *
 * Guides a user from a bare server to a fully configured Last Light instance.
 * Uses @clack/prompts for the interactive UI and chalk for styling.
 */

import { randomBytes } from "node:crypto";
import {
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
  mkdirSync,
  chmodSync,
  copyFileSync,
  symlinkSync,
  lstatSync,
  unlinkSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { execSync } from "node:child_process";
import * as p from "@clack/prompts";
import chalk from "chalk";
import { OVERLAY_GITIGNORE, detectGh, bootstrapOverlayRepo } from "../config/overlay-bootstrap.js";
import { serverUpdate } from "./cli-server.js";
import { PROVIDERS, providerByPrefix, OAUTH_PROVIDERS, oauthProviderById, type ProviderSpec } from "../providers.js";

// ── Brand colors ───────────────────────────────────────────────────────────

const gold = chalk.hex("#F0B429");
const teal = chalk.hex("#1A7A8A");
const orange = chalk.hex("#E8752A");
const dim = chalk.dim;
const bright = chalk.white.bold;

// ── Types ───────────────────────────────────────────────────────────────────

export interface SetupConfig {
  /**
   * GitHub integration tier. `undefined` is treated as `app` for backward
   * compatibility. `app` = full GitHub App + webhook; `pat` = a read-only
   * Personal Access Token, CLI-driven, no webhook; `chat` = no GitHub at all.
   */
  mode?: "app" | "pat" | "chat";
  /** GitHub App fields — set only in `app` mode. */
  GITHUB_APP_ID?: string;
  GITHUB_APP_INSTALLATION_ID?: string;
  WEBHOOK_SECRET?: string;
  /** Personal Access Token — set only in `pat` mode. */
  GITHUB_TOKEN?: string;
  ADMIN_SECRET: string;
  DOMAIN: string;
  /** Model id consumed by agentic-pi / pi-ai, e.g. "anthropic/claude-sonnet-4-6" or "openai/gpt-5.5". */
  LASTLIGHT_MODEL: string;
  /**
   * The chosen provider's API key, set by the wizard. The runtime reads the
   * matching env var (named per `ProviderSpec.envKey`), so we keep the raw
   * value + the env var name and let `buildEnvContent()` serialise the right
   * line. Older versions hard-coded `OPENAI_API_KEY` / `ANTHROPIC_API_KEY` /
   * `OPENROUTER_API_KEY` — those are now passed through verbatim when the
   * user picks one of those providers, so existing .env files keep working.
   */
  providerApiKey: { envKey: string; value: string } | undefined;
  /** Back-compat shims preserving the legacy fields for older callers/tests. */
  ADMIN_PASSWORD?: string;
  SLACK_BOT_TOKEN?: string;
  SLACK_APP_TOKEN?: string;
  SLACK_DELIVERY_CHANNEL?: string;
  SLACK_ALLOWED_USERS?: string;
  useCaddy: boolean;
  /** Path to the GitHub App PEM — set only in `app` mode. */
  pemSourcePath?: string;
  /** Repositories the bot manages — written to instance/config.yaml (the overlay). */
  managedRepos: string[];
}

// ── Validation helpers (exported for unit tests) ────────────────────────────

export function isPositiveInt(s: string): boolean {
  return /^\d+$/.test(s) && parseInt(s, 10) > 0;
}

/**
 * Try to resolve a PEM path. Checks: as given, relative to cwd, relative
 * to parent dir (for when the wizard chdir'd into a clone), and with ~ expanded.
 * Returns the resolved absolute path or null if not found.
 */
function resolvePem(input: string): string | null {
  let expanded = input;
  if (expanded.startsWith("~/")) {
    expanded = join(process.env.HOME || "", expanded.slice(2));
  }
  const candidates = [
    resolve(expanded),
    resolve("..", expanded),
  ];
  for (const candidate of candidates) {
    if (isPemFile(candidate)) return candidate;
  }
  return null;
}

export function isPemFile(filePath: string): boolean {
  try {
    const content = readFileSync(filePath, "utf8");
    return (
      content.startsWith("-----BEGIN RSA PRIVATE KEY-----") ||
      content.startsWith("-----BEGIN PRIVATE KEY-----")
    );
  } catch {
    return false;
  }
}

export function isSlackBotToken(s: string): boolean {
  return s.startsWith("xoxb-");
}

export function isSlackAppToken(s: string): boolean {
  return s.startsWith("xapp-");
}

// ── .env serialization (exported for unit tests) ────────────────────────────

export function buildEnvContent(config: SetupConfig): string {
  // `undefined` mode is treated as `app` for backward compatibility.
  const mode = config.mode ?? "app";
  const lines: string[] = [
    "# ── Last Light — Environment Variables ─────────────────────",
    "# Generated by: npx lastlight setup",
    "",
    "# ── Overlay (this deployment's private config + assets) ──",
    "LASTLIGHT_OVERLAY_DIR=/app/instance",
    "",
  ];
  if (mode === "app") {
    lines.push(
      "# ── GitHub App (required) ────────────────────────────────",
      `GITHUB_APP_ID=${config.GITHUB_APP_ID}`,
      // PEM lives at instance/secrets/app.pem; the entrypoint symlinks it to /app/app.pem.
      `GITHUB_APP_PRIVATE_KEY_PATH=./app.pem`,
      `GITHUB_APP_INSTALLATION_ID=${config.GITHUB_APP_INSTALLATION_ID}`,
      "",
      "# ── Webhook (required) ──────────────────────────────────",
      `WEBHOOK_SECRET=${config.WEBHOOK_SECRET}`,
      "",
    );
  } else if (mode === "pat") {
    lines.push(
      "# ── GitHub (Personal Access Token — read-only, CLI-driven) ──",
      "# No GitHub App / webhook. Trigger workflows from the `lastlight` CLI.",
      `GITHUB_TOKEN=${config.GITHUB_TOKEN}`,
      "",
    );
  } else {
    lines.push(
      "# ── GitHub: none (chat-only mode) ────────────────────────",
      "# Interact via `lastlight chat` and the dashboard.",
      "",
    );
  }
  lines.push(
    "# ── Domain (used by Caddy for TLS) ─────────────────────────────────────",
    `DOMAIN=${config.DOMAIN}`,
    "",
    "# ── Model + provider API key ────────────────────────────────",
    `LASTLIGHT_MODEL=${config.LASTLIGHT_MODEL}`,
    "# Set the env var that matches your LASTLIGHT_MODEL's provider.",
    "# See src/providers.ts for the full registry (anthropic, openai,",
    "# openrouter, google, mistral, groq, cerebras, xai, huggingface,",
    "# moonshotai, nvidia, fireworks, together, deepseek, zai,",
    "# kimi-coding, minimax).",
  );
  if (config.providerApiKey) {
    lines.push(`${config.providerApiKey.envKey}=${config.providerApiKey.value}`);
  }
  lines.push(
    "",
    "# ── Admin Dashboard ────────────────────────────────────────",
    `ADMIN_SECRET=${config.ADMIN_SECRET}`,
  );

  if (config.ADMIN_PASSWORD) {
    lines.push(`ADMIN_PASSWORD=${config.ADMIN_PASSWORD}`);
  }

  if (config.SLACK_BOT_TOKEN) {
    lines.push("");
    lines.push("# ── Slack ──────────────────────────────────────────────────");
    lines.push(`SLACK_BOT_TOKEN=${config.SLACK_BOT_TOKEN}`);
    if (config.SLACK_APP_TOKEN) {
      lines.push(`SLACK_APP_TOKEN=${config.SLACK_APP_TOKEN}`);
    }
    if (config.SLACK_DELIVERY_CHANNEL) {
      lines.push(`SLACK_DELIVERY_CHANNEL=${config.SLACK_DELIVERY_CHANNEL}`);
    }
    if (config.SLACK_ALLOWED_USERS) {
      lines.push(`SLACK_ALLOWED_USERS=${config.SLACK_ALLOWED_USERS}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

/** Build the overlay config.yaml (instance/config.yaml) — merged over config/default.yaml. */
export function buildOverlayConfig(config: SetupConfig): string {
  const lines = [
    "# Last Light — private deployment overlay config",
    "# Merged over the public config/default.yaml at startup; arrays replace,",
    "# maps deep-merge, env vars override. Restart the agent to apply:",
    "#   docker compose restart agent",
    "",
    "managedRepos:",
  ];
  if (config.managedRepos.length === 0) {
    lines.push("  []  # add owner/repo entries — the bot ignores repos not listed here");
  } else {
    for (const repo of config.managedRepos) lines.push(`  - ${repo}`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Compose override (overlay): disable Caddy when the operator opts out of its TLS. */
export const CADDY_DISABLED_OVERRIDE = [
  "# Deployment compose override — version-controlled in the overlay (instance/).",
  "# Symlinked into the project dir as ./docker-compose.override.yml so",
  "# `docker compose` auto-loads it on top of the repo's docker-compose.yml.",
  "# This deployment opted out of Caddy TLS at setup time.",
  "services:",
  "  caddy:",
  "    profiles:",
  "      - disabled",
  "",
].join("\n");

const OVERRIDE_FILE = "docker-compose.override.yml";

/**
 * Symlink the overlay's compose override into the project dir so plain
 * `docker compose` auto-discovers it (Compose only auto-loads
 * ./docker-compose.override.yml). No-op if the overlay has no override.
 * Leaves a pre-existing regular file untouched.
 */
export function ensureOverrideSymlink(): void {
  const target = join("instance", OVERRIDE_FILE);
  if (!existsSync(target)) return;
  let existing: ReturnType<typeof lstatSync> | undefined;
  try {
    existing = lstatSync(OVERRIDE_FILE);
  } catch {
    /* link absent */
  }
  if (existing && !existing.isSymbolicLink()) {
    p.log.warn(`${OVERRIDE_FILE} already exists as a regular file — leaving it; not symlinking the overlay override.`);
    return;
  }
  if (existing) unlinkSync(OVERRIDE_FILE);
  symlinkSync(target, OVERRIDE_FILE);
  p.log.success(dim(`${OVERRIDE_FILE}`) + " → " + dim(target));
}

// ── Clack helper — bail on cancel ───────────────────────────────────────────

function required<T>(value: T | symbol): T {
  if (p.isCancel(value)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }
  return value;
}

// ── Banner ──────────────────────────────────────────────────────────────────

function printBanner(): void {
  // Inner width = 46 chars between the box-drawing borders
  const W = 46;
  const pad = (text: string, styled: string) => {
    const left = Math.floor((W - text.length) / 2);
    const right = W - text.length - left;
    return gold("  │") + " ".repeat(left) + styled + " ".repeat(right) + gold("│");
  };
  const empty = gold("  │") + " ".repeat(W) + gold("│");
  const rule = "─".repeat(W);

  console.log();
  console.log(gold(`  ╭${rule}╮`));
  console.log(empty);
  console.log(pad("✦  L A S T   L I G H T  ✦", bright("✦  L A S T   L I G H T  ✦")));
  console.log(empty);
  console.log(pad("GitHub Repository Maintenance Agent", dim("GitHub Repository Maintenance Agent")));
  console.log(empty);
  console.log(gold(`  ╰${rule}╯`));
  console.log();
}

// ── Preflight ───────────────────────────────────────────────────────────────

function preflight(): void {
  if (!existsSync("docker-compose.yml")) {
    if (existsSync("lastlight/docker-compose.yml")) {
      p.log.info("Found existing lastlight/ directory — continuing setup there.");
      process.chdir("lastlight");
    } else {
      const s = p.spinner();
      s.start("Cloning nearform/lastlight ...");
      try {
        execSync("git clone https://github.com/nearform/lastlight.git lastlight", {
          stdio: "pipe",
        });
        s.stop("Repository cloned.");
      } catch {
        s.stop("Clone failed.");
        p.log.error("Failed to clone. Please clone manually:");
        p.log.info("  git clone https://github.com/nearform/lastlight.git");
        process.exit(1);
      }
      process.chdir("lastlight");
      p.log.info(`Working directory: ${dim(process.cwd())}`);
    }
  }

  try {
    execSync("docker info", { stdio: "ignore" });
  } catch {
    p.log.error("Docker is not running or not installed.");
    p.log.info("Please start Docker and re-run: " + teal("npx lastlight setup"));
    process.exit(1);
  }

  if (existsSync(join("instance", "secrets", ".env"))) {
    p.log.error(
      "instance/secrets/.env already exists. To reconfigure, remove it first: " +
        dim("rm instance/secrets/.env"),
    );
    process.exit(1);
  }
}

// ── Setup steps ─────────────────────────────────────────────────────────────

async function collectGitHubApp(): Promise<{
  appId: string;
  installationId: string;
  pemSourcePath: string;
}> {
  p.log.step(gold("GitHub App"));
  p.log.info(
    dim("Create one at ") +
    teal("https://github.com/settings/apps/new") +
    dim(" if you haven't already.")
  );

  const appId = required(
    await p.text({
      message: "GitHub App ID",
      placeholder: "123456",
      validate: (v) =>
        v && isPositiveInt(v) ? undefined : "Must be a positive integer.",
    }),
  );

  const installationId = required(
    await p.text({
      message: "Installation ID",
      placeholder: "789012",
      validate: (v) =>
        v && isPositiveInt(v) ? undefined : "Must be a positive integer.",
    }),
  );

  // Search cwd and parent for .pem files to offer as choices
  const pemCandidates: string[] = [];
  for (const dir of [process.cwd(), resolve("..")]) {
    try {
      for (const f of readdirSync(dir)) {
        if (f.endsWith(".pem")) {
          const full = join(dir, f);
          if (isPemFile(full)) pemCandidates.push(full);
        }
      }
    } catch { /* unreadable dir */ }
  }

  let pemResolved: string;
  if (pemCandidates.length > 0) {
    const choice = required(
      await p.select({
        message: "Private key (.pem)",
        options: [
          ...pemCandidates.map((f) => ({ value: f, label: f.replace(process.env.HOME || "", "~") })),
          { value: "__other__", label: dim("Enter a different path...") },
        ],
      }),
    ) as string;

    if (choice === "__other__") {
      const manual = required(
        await p.text({
          message: "Path to private key (.pem)",
          validate: (v) => {
            if (!v) return "Enter a file path.";
            return resolvePem(v) ? undefined : "File not found or not a valid PEM.";
          },
        }),
      );
      pemResolved = resolvePem(manual as string)!;
    } else {
      pemResolved = choice;
    }
  } else {
    const manual = required(
      await p.text({
        message: "Path to private key (.pem)",
        placeholder: "~/downloads/your-app.private-key.pem",
        validate: (v) => {
          if (!v) return "Enter a file path.";
          return resolvePem(v) ? undefined : "File not found or not a valid PEM.";
        },
      }),
    );
    pemResolved = resolvePem(manual as string)!;
  }

  return {
    appId: appId as string,
    installationId: installationId as string,
    pemSourcePath: pemResolved,
  };
}

/**
 * Choose the GitHub integration tier. `app` is the full agent (webhooks +
 * repo-write); `pat` is a read-only, CLI-driven setup that's far easier to
 * stand up (just a token); `chat` skips GitHub entirely.
 */
async function collectMode(): Promise<"app" | "pat" | "chat"> {
  p.log.step(gold("GitHub integration"));
  return required(
    await p.select({
      message: "How should Last Light connect to GitHub?",
      options: [
        { value: "app", label: "Full GitHub App", hint: "webhooks + repo-write; the complete agent" },
        { value: "pat", label: "Personal Access Token", hint: "read-only, CLI-driven; no webhook/App setup" },
        { value: "chat", label: "Chat-only (no GitHub)", hint: "just the CLI chat + dashboard" },
      ],
      initialValue: "app",
    }),
  ) as "app" | "pat" | "chat";
}

/** Collect a read-only Personal Access Token for `pat` mode. */
async function collectPat(): Promise<string> {
  p.log.step(gold("GitHub token"));
  p.log.info(
    dim("Create a fine-grained token (read-only is safest) at ") +
    teal("https://github.com/settings/personal-access-tokens/new") +
    dim(". Grant read access to the repos you'll manage."),
  );
  return required(
    await p.text({
      message: "GitHub Personal Access Token",
      placeholder: "github_pat_… or ghp_…",
      validate: (v) => (v && v.trim().length > 0 ? undefined : "Enter a token."),
    }),
  ) as string;
}

async function collectDomain(): Promise<{ domain: string; useCaddy: boolean }> {
  p.log.step(gold("Domain & TLS"));

  const domain = required(
    await p.text({
      message: "Your domain",
      placeholder: "lastlight.example.com",
      validate: (v) =>
        v && v.length > 0 && v.includes(".")
          ? undefined
          : "Enter a valid domain name.",
    }),
  );

  const useCaddy = required(
    await p.confirm({
      message: "Use Caddy for automatic TLS?",
      initialValue: true,
    }),
  );

  p.log.info(`Webhook URL: ${teal(`https://${domain}/webhook`)}`);

  return { domain: domain as string, useCaddy: useCaddy as boolean };
}

/** Parse a free-text list of `owner/repo` entries (comma/space/newline separated). */
export function parseManagedRepos(input: string): string[] {
  const seen = new Set<string>();
  for (const tok of input.split(/[\s,]+/).map((t) => t.trim()).filter(Boolean)) {
    if (/^[^/\s]+\/[^/\s]+$/.test(tok)) seen.add(tok);
  }
  return [...seen];
}

async function collectManagedRepos(): Promise<string[]> {
  p.log.step(gold("Managed repositories"));
  p.log.info(dim("Repos the bot will operate on. Install the GitHub App on each. Add more later in instance/config.yaml."));

  const raw = required(
    await p.text({
      message: "Managed repos (owner/repo, space- or comma-separated)",
      placeholder: "your-org/repo-one your-org/repo-two",
      validate: (v) => {
        if (!v || !v.trim()) return undefined; // allow empty — can fill in later
        return parseManagedRepos(v).length > 0 ? undefined : "Use owner/repo form, e.g. acme/widgets.";
      },
    }),
  );

  const repos = parseManagedRepos((raw as string) || "");
  if (repos.length === 0) {
    p.log.warn("No managed repos set — the bot won't act until you add some to instance/config.yaml.");
  } else {
    p.log.success(`Managing ${repos.length} repo${repos.length === 1 ? "" : "s"}: ${dim(repos.join(", "))}`);
  }
  return repos;
}

/**
 * Result of the step-4 model+key collector. The wizard picks a provider from
 * the shared registry (`src/providers.ts`), then asks for the model id and
 * the provider's API key. The key is returned tagged with the env var name
 * the runtime expects, so `buildEnvContent()` can serialise the right line.
 */
async function collectModelAndKey(): Promise<{
  model: string;
  /** Undefined for OAuth (subscription-login) providers — they use auth.json, not an env key. */
  providerApiKey: { envKey: string; value: string } | undefined;
}> {
  p.log.step(gold("Model provider"));
  p.log.info(
    dim("agentic-pi (pi-ai) is provider-agnostic and supports 15+ providers — ") +
    dim("Anthropic, OpenAI, Google, Mistral, Groq, Cerebras, xAI, Hugging Face, ") +
    dim("Moonshot, NVIDIA, Fireworks, Together, DeepSeek, Z.AI, OpenRouter, …"),
  );

  // Provider picker — the registry is the single source of truth. Order is
  // intentional: Anthropic (default) → OpenAI → Google → the rest grouped by
  // family. The "custom" escape hatch lets the user enter any `provider/model`
  // string pi-ai accepts even if we haven't surfaced a register entry.
  const defaultPrefix = "anthropic";
  const providerChoice = required(
    await p.select({
      message: `Provider ${dim("(model spec prefix)")}`,
      initialValue: defaultPrefix,
      options: [
        // Render every registered provider; the option value is the prefix.
        ...PROVIDERS.map((spec) => ({
          value: spec.prefix,
          label:
            spec.prefix === defaultPrefix
              ? `${spec.displayName} ${dim("(default)")}`
              : spec.displayName,
          hint: spec.prefix,
        })),
        // OAuth (subscription-login) providers — no API key; the user logs in
        // separately via `lastlight oauth login`. Value tagged `oauth:<id>`.
        ...OAUTH_PROVIDERS.map((o) => ({
          value: `oauth:${o.id}`,
          label: `${o.displayName} ${dim("(OAuth login)")}`,
          hint: o.modelPrefix,
        })),
        { value: "__custom__", label: dim("Enter a custom provider/model...") },
      ],
    }),
  ) as string;

  // OAuth branch: no API key. Pick a model id, return a key-less result, and
  // remind the user to run the login after setup (the browser flow writes
  // auth.json, not the .env this wizard produces).
  if (providerChoice.startsWith("oauth:")) {
    const oauth = oauthProviderById(providerChoice.slice("oauth:".length))!;
    const sampleId = oauth.sampleModel.slice(oauth.sampleModel.indexOf("/") + 1);
    const customModelId = required(
      await p.text({
        message: `Model id for ${oauth.displayName} ${dim("(provider prefix added automatically)")}`,
        placeholder: sampleId,
        defaultValue: sampleId,
        validate: (v) =>
          !v || !v.trim() || /^[A-Za-z0-9][\w/.-]*$/.test(v)
            ? undefined
            : "Use the model id (e.g. gpt-5.4).",
      }),
    ) as string;
    const model = `${oauth.modelPrefix}/${(customModelId || sampleId).trim()}`;
    p.log.success(`Model: ${teal(model)} — auth: ${dim("OAuth (subscription login)")}`);
    p.note(
      `After setup finishes, log in on this host:\n\n  ${teal(`lastlight oauth login ${oauth.id}`)}\n\n` +
        (oauth.sandboxEnvVar
          ? dim("Works for chat and sandbox workflows.")
          : dim("Chat only — sandbox workflows can't use this provider (no env-token route).")),
      "One more step",
    );
    return { model, providerApiKey: undefined };
  }

  let spec: ProviderSpec;
  let modelId: string;
  if (providerChoice === "__custom__") {
    const raw = required(
      await p.text({
        message: "provider/model",
        placeholder: "openai/gpt-5.3-codex or anthropic/claude-…",
        validate: (v) => {
          if (!v || !/^[a-z][\w-]*\//.test(v)) {
            return "Format must be provider/model (e.g. openai/gpt-5.3-codex).";
          }
          const prefix = v.split("/")[0].toLowerCase();
          if (!providerByPrefix(prefix)) {
            return (
              `Unknown provider prefix "${prefix}". Registered providers: ` +
              PROVIDERS.map((s) => s.prefix).join(", ")
            );
          }
          return undefined;
        },
      }),
    ) as string;
    const slashIdx = raw.indexOf("/");
    const prefix = raw.slice(0, slashIdx).toLowerCase();
    spec = providerByPrefix(prefix)!;
    modelId = raw.slice(slashIdx + 1);
  } else {
    spec = providerByPrefix(providerChoice)!;
    // Default to the canonical primary model for this provider (the user can
    // override in the next prompt).
    modelId = spec.sampleModel;
    const customModelId = required(
      await p.text({
        message: `Model id for ${spec.displayName} ${dim("(provider prefix is added automatically)")}`,
        placeholder: spec.sampleModel,
        defaultValue: spec.sampleModel,
        validate: (v) => {
          if (!v || !v.trim()) return undefined; // accept the default on Enter
          // The user enters the model id without the provider prefix; keep
          // OpenRouter's nested `vendor/model` tail legal.
          return /^[A-Za-z0-9][\w/.-]*$/.test(v) ? undefined : "Use the model id (e.g. claude-sonnet-4-6 or anthropic/claude-sonnet-4.5 for OpenRouter).";
        },
      }),
    ) as string;
    modelId = (customModelId || spec.sampleModel).trim();
  }

  const model = `${spec.prefix}/${modelId}`;

  // Provider-specific API key. We surface the right env var name + a
  // known-prefix hint; validation is loose (the upstream will reject a wrong
  // key with a clear error, so we don't gate the install on shape alone).
  const keyPlaceholder = spec.keyPrefix ? `${spec.keyPrefix}…` : "paste your key";
  const key = required(
    await p.text({
      message: spec.envKey,
      placeholder: keyPlaceholder,
      validate: (v) => {
        if (!v || !v.trim()) return "Enter a non-empty API key.";
        if (spec.keyPrefix && !v.startsWith(spec.keyPrefix)) {
          return `Keys for ${spec.displayName} usually start with "${spec.keyPrefix}". Paste yours to override.`;
        }
        return undefined;
      },
    }),
  ) as string;

  p.log.success(`Model: ${teal(model)} — key: ${dim(spec.envKey)}`);
  return { model, providerApiKey: { envKey: spec.envKey, value: key.trim() } };
}

async function collectAdminPassword(): Promise<string | undefined> {
  p.log.step(gold("Admin Dashboard"));

  const wantPassword = required(
    await p.confirm({
      message: "Set an admin dashboard password?",
      initialValue: false,
    }),
  );
  if (!wantPassword) return undefined;

  const password = required(
    await p.password({
      message: "Admin password",
      validate: (v) =>
        v && v.length >= 8 ? undefined : "Must be at least 8 characters.",
    }),
  );

  return password as string;
}

async function collectSlack(): Promise<{
  botToken?: string;
  appToken?: string;
  deliveryChannel?: string;
  allowedUsers?: string;
}> {
  p.log.step(gold("Slack") + dim(" (optional)"));

  const wantSlack = required(
    await p.confirm({
      message: "Enable Slack integration?",
      initialValue: false,
    }),
  );
  if (!wantSlack) return {};

  const botToken = required(
    await p.text({
      message: "SLACK_BOT_TOKEN",
      placeholder: "xoxb-...",
      validate: (v) =>
        v && isSlackBotToken(v) ? undefined : "Must start with xoxb-",
    }),
  ) as string;

  const appToken = required(
    await p.text({
      message: "SLACK_APP_TOKEN",
      placeholder: "xapp-...",
      validate: (v) =>
        v && isSlackAppToken(v) ? undefined : "Must start with xapp-",
    }),
  ) as string;

  const deliveryChannel = required(
    await p.text({
      message: "Delivery channel ID",
      placeholder: "C0123456789 (press Enter to skip)",
      defaultValue: "",
    }),
  ) as string;

  const allowedUsers = required(
    await p.text({
      message: "Allowed user IDs",
      placeholder: "U0123,U0456 (press Enter to skip)",
      defaultValue: "",
    }),
  ) as string;

  return {
    botToken,
    appToken,
    deliveryChannel: deliveryChannel || undefined,
    allowedUsers: allowedUsers || undefined,
  };
}

function writeConfig(config: SetupConfig): void {
  p.log.step(gold("Writing config"));

  const secretsDir = join("instance", "secrets");
  try {
    mkdirSync(secretsDir, { recursive: true });
  } catch (err: unknown) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === "EACCES") {
      p.log.error("Permission denied creating instance/secrets/ directory.");
      process.exit(1);
    }
    throw err;
  }

  // Secrets → instance/secrets/ (mounted at /app/instance, never committed/baked).
  // Only `app` mode has a PEM to copy.
  const hasPem = !!config.pemSourcePath;
  if (config.pemSourcePath) {
    copyFileSync(config.pemSourcePath, join(secretsDir, "app.pem"));
    chmodSync(join(secretsDir, "app.pem"), 0o600);
  }

  const envContent = buildEnvContent(config);
  writeFileSync(join(secretsDir, ".env"), envContent, { encoding: "utf8" });
  chmodSync(join(secretsDir, ".env"), 0o600);

  // Overlay config + .gitignore so instance/ can become a private repo.
  writeFileSync(join("instance", "config.yaml"), buildOverlayConfig(config), { encoding: "utf8" });
  if (!existsSync(join("instance", ".gitignore"))) {
    writeFileSync(join("instance", ".gitignore"), OVERLAY_GITIGNORE, { encoding: "utf8" });
  }

  // Opted out of Caddy → disable it via an overlay compose override.
  const overlayOverride = join("instance", OVERRIDE_FILE);
  if (!config.useCaddy && !existsSync(overlayOverride)) {
    writeFileSync(overlayOverride, CADDY_DISABLED_OVERRIDE, { encoding: "utf8" });
  }
  // Symlink the overlay override (generated above, or pre-existing from a
  // cloned overlay) into the project dir so `docker compose` auto-loads it.
  ensureOverrideSymlink();

  p.log.success(
    (hasPem ? dim("instance/secrets/app.pem") + " copied " + dim("(mode 600)") + "\n  " : "") +
    dim("instance/secrets/.env") + " written " + dim("(mode 600)") + "\n" +
    "  " + dim("instance/config.yaml") + " written " + dim(`(${config.managedRepos.length} managed repo${config.managedRepos.length === 1 ? "" : "s"})`)
  );
}


async function dockerBuildAndLaunch(): Promise<void> {
  p.log.step(gold("Docker"));

  const wantLaunch = required(
    await p.confirm({
      message: "Build and launch Last Light now?",
      initialValue: true,
    }),
  );

  if (!wantLaunch) {
    p.log.info("When ready, run: " + teal("lastlight server start"));
    return;
  }

  // Delegate to the canonical deploy flow (`lastlight server update`) instead
  // of re-implementing build/launch here. It builds the agent + sandbox-base +
  // sandbox + sandbox-qa images, brings the stack up, restarts the egress sidecars, and
  // health-checks — all with inherited stdio so the user sees live progress
  // (docker build layers) rather than a silent spinner. The checkout is already
  // current and the overlay was just written, so skip the git pulls.
  await serverUpdate({ home: process.cwd(), core: false, overlay: false, build: true });
}

function printSummary(mode: "app" | "pat" | "chat", domain: string, webhookSecret?: string): void {
  console.log();
  console.log(gold("  ┌──────────────────────────────────────────────┐"));
  console.log(gold("  │") + bright("  Setup complete!                              ") + gold("│"));
  console.log(gold("  └──────────────────────────────────────────────┘"));
  console.log();
  if (mode === "app") {
    console.log("  " + dim("Webhook URL   ") + teal(`https://${domain}/webhook`));
  }
  console.log("  " + dim("Dashboard     ") + teal(`https://${domain}/admin`));
  console.log();
  if (mode === "app" && webhookSecret) {
    console.log("  " + orange("Paste this WEBHOOK_SECRET into your GitHub App settings:"));
    console.log("  " + bright(webhookSecret));
    console.log();
  }
  console.log("  " + dim("Next steps:"));
  console.log("  " + dim("  • Tune ") + teal("instance/config.yaml") + dim(" (managed repos, models, overrides), then ") + teal("docker compose restart agent"));
  console.log("  " + dim("  • Push later edits to your overlay repo, then ") + teal("lastlight server restart agent"));
  if (mode === "app") {
    console.log("  " + dim("  • Verify webhook delivery in GitHub App settings"));
  } else if (mode === "pat") {
    console.log("  " + dim("  • Trigger read-only workflows from the CLI: ") + teal("lastlight triage owner/repo"));
  } else {
    console.log("  " + dim("  • Chat with the bot: ") + teal("lastlight chat"));
  }
  console.log("  " + dim("  • Check logs: ") + teal("docker compose logs -f") + dim(" (or docker-compose)"));
  console.log();
}

// ── Main entry point ─────────────────────────────────────────────────────────

export async function runSetup(): Promise<void> {
  if (!process.stdin.isTTY) {
    console.error("Error: setup must be run interactively (stdin must be a TTY).");
    process.exit(1);
  }

  printBanner();

  p.intro(dim("This wizard will configure Last Light on your server."));

  preflight();

  const mode = await collectMode();

  // GitHub auth — collected per mode. `app` needs App id/installation/PEM +
  // a webhook secret; `pat` needs just a token; `chat` needs nothing.
  let appId: string | undefined;
  let installationId: string | undefined;
  let pemSourcePath: string | undefined;
  let webhookSecret: string | undefined;
  let githubToken: string | undefined;
  if (mode === "app") {
    ({ appId, installationId, pemSourcePath } = await collectGitHubApp());
    webhookSecret = randomBytes(32).toString("hex");
  } else if (mode === "pat") {
    githubToken = await collectPat();
  }
  const adminSecret = randomBytes(32).toString("hex");
  p.log.success(
    "Secrets auto-generated " +
      dim(mode === "app" ? "(WEBHOOK_SECRET + ADMIN_SECRET)" : "(ADMIN_SECRET)"),
  );

  const { domain, useCaddy } = await collectDomain();
// Managed repos are meaningful for App + PAT; chat-only has no repos to manage.
  const managedRepos = mode === "chat" ? [] : await collectManagedRepos();
  const { model, providerApiKey } = await collectModelAndKey();
  const adminPassword = await collectAdminPassword();
  const { botToken, appToken, deliveryChannel, allowedUsers } = await collectSlack();

  const config: SetupConfig = {
    mode,
    GITHUB_APP_ID: appId,
    GITHUB_APP_INSTALLATION_ID: installationId,
    WEBHOOK_SECRET: webhookSecret,
    GITHUB_TOKEN: githubToken,
    ADMIN_SECRET: adminSecret,
    DOMAIN: domain,
    LASTLIGHT_MODEL: model,
    providerApiKey,
    ADMIN_PASSWORD: adminPassword,
    SLACK_BOT_TOKEN: botToken,
    SLACK_APP_TOKEN: appToken,
    SLACK_DELIVERY_CHANNEL: deliveryChannel,
    SLACK_ALLOWED_USERS: allowedUsers,
    useCaddy,
    pemSourcePath,
    managedRepos,
  };

  writeConfig(config);

  // Offer to version the freshly-scaffolded overlay + create a private GitHub repo.
  p.log.step(gold("Version overlay"));
  await bootstrapOverlayRepo(resolve("instance"), { gh: await detectGh() });

  await dockerBuildAndLaunch();

  p.outro(gold("Last Light is ready."));
  printSummary(mode, domain, webhookSecret);
}
