import { readFileSync, readdirSync } from "fs";
import { join, resolve } from "path";
import type { GitHubTokenPermissions } from "./git-auth.js";

/**
 * Default directory for agent context files (soul, rules, etc.). Concatenated
 * into AGENTS.md inside the sandbox by the entrypoint; the harness only reads
 * this when assembling a system prompt for non-sandbox paths.
 */
const AGENT_CONTEXT_DIR = resolve("agent-context");

/**
 * Configuration for the executor.
 */
export interface ExecutorConfig {
  /** Path to the MCP server config for GitHub tools (kept for legacy callers). */
  mcpConfigPath: string;
  /** Working directory for the agent (used by the direct-fallback path). */
  cwd?: string;
  /** Maximum conversation turns. Unused by OpenCode runtime; kept for API stability. */
  maxTurns?: number;
  /** Model id passed to the runtime (e.g. "openai/gpt-5.3-codex"). */
  model?: string;
  /** Path to agent context directory. */
  agentContextDir?: string;
  /** Directory for persistent state. */
  stateDir?: string;
  /** Directory for agent sandboxes (cloned repos). */
  sandboxDir?: string;
}

/**
 * Result from an agent execution.
 */
export interface ExecutionResult {
  success: boolean;
  output: string;
  turns: number;
  error?: string;
  durationMs: number;
  /** Session id captured from the runtime's stream. */
  sessionId?: string;
  /** Total USD cost reported by the runtime. Zero under OAuth/subscription auth. */
  costUsd?: number;
  /** Tokens billed as fresh input (no cache hit). */
  inputTokens?: number;
  /** Tokens that triggered a cache write. */
  cacheCreationInputTokens?: number;
  /** Tokens served from prompt cache (heavily discounted). */
  cacheReadInputTokens?: number;
  /** Output tokens generated by the model. */
  outputTokens?: number;
  /** API-side duration (excludes orchestrator overhead). */
  apiDurationMs?: number;
  /** Mapped stop reason ("success" / "error_*" / etc.). */
  stopReason?: string;
}

export type GitAccessProfile = "read" | "issues-write" | "review-write" | "repo-write";

export interface GitSandboxAccess {
  owner: string;
  repo: string;
  profile: GitAccessProfile;
  /**
   * When true, sandbox MCP can mint/refresh tokens using the app PEM.
   * Leave false for lower-trust runs to keep private key material inaccessible.
   */
  allowMcpAppAuth?: boolean;
}

export const GITHUB_PERMISSION_PROFILES: Record<GitAccessProfile, GitHubTokenPermissions> = {
  read: {
    contents: "read",
    issues: "read",
    pull_requests: "read",
    metadata: "read",
  },
  "issues-write": {
    contents: "read",
    issues: "write",
    pull_requests: "read",
    metadata: "read",
  },
  "review-write": {
    contents: "read",
    issues: "write",
    pull_requests: "write",
    metadata: "read",
  },
  "repo-write": {
    contents: "write",
    issues: "write",
    pull_requests: "write",
    metadata: "read",
  },
};

/**
 * Load all .md files from the agent-context directory and concatenate them
 * into a single string. The sandbox entrypoint does this independently to
 * produce AGENTS.md; this helper exists for in-process callers (e.g. chat).
 */
export function loadAgentContext(dir?: string): string {
  const contextDir = dir || AGENT_CONTEXT_DIR;
  try {
    const files = readdirSync(contextDir)
      .filter((f) => f.endsWith(".md"))
      .sort();
    return files
      .map((f) => readFileSync(join(contextDir, f), "utf-8"))
      .join("\n\n---\n\n");
  } catch {
    console.warn(`[executor] No agent context found at ${contextDir}`);
    return "";
  }
}

// `executeAgent` lives in opencode-executor.ts. Re-exported here so existing
// imports (`import { executeAgent } from "./executor.js"`) and test mocks
// (`vi.mock("../engine/executor.js", …)`) keep working unchanged.
export { executeAgent } from "./opencode-executor.js";
