import type { GitHubTokenPermissions } from "./git-auth.js";
import type { OtelConfig, SandboxBackend } from "../config.js";
import { loadAgentContext as loadResolvedAgentContext } from "../workflows/loader.js";

/**
 * Configuration for an agent execution.
 */
export interface ExecutorConfig {
  /** Working directory for the agent (used by the no-sandbox path). */
  cwd?: string;
  /** Maximum conversation turns. Unused by agentic-pi; kept for API stability. */
  maxTurns?: number;
  /** Model id (e.g. "anthropic/claude-sonnet-4-6"). */
  model?: string;
  /**
   * Pi thinking level: `off | minimal | low | medium | high | xhigh`.
   * Forwarded to agentic-pi as the `thinking` option. When omitted,
   * agentic-pi uses the model's default.
   */
  variant?: string;
  /** Path to agent context directory. */
  agentContextDir?: string;
  /** Directory for persistent state. */
  stateDir?: string;
  /** Directory for agent sandboxes (cloned repos). */
  sandboxDir?: string;
  /** Where the shim writes dashboard envelope jsonl. */
  sessionsDir?: string;
  /** Workflow sandbox backend (overrides config-level default). */
  sandbox?: SandboxBackend;
  /**
   * Bypass the HTTP egress allowlist for this phase. When true:
   *   - gondolin: `allowedHttpHosts: ["*"]` is passed to agentic-pi.
   *   - docker:   the sandbox container uses the open CoreDNS/nginx
   *               egress-firewall pair instead of the strict one.
   *
   * Default false. Set via the `unrestricted_egress` field on a workflow
   * phase — used for phases that need broad web access (e.g. an explore
   * phase that searches third-party documentation).
   */
  unrestrictedEgress?: boolean;
  /**
   * Enable agentic-pi's web-search extension (`web_search` / `web_fetch`
   * tools). Default false. agentic-pi auto-enables web search whenever a
   * provider env var (`TAVILY_API_KEY`, `BRAVE_SEARCH_API_KEY`,
   * `EXA_API_KEY`) is present, so we pass an explicit `false` downstream
   * to suppress auto-enable for non-explore workflows.
   */
  webSearch?: boolean;
  /**
   * Force a specific web-search provider. When unset, agentic-pi picks
   * one based on which API key env var is present (Tavily > Exa > Brave).
   */
  webSearchProvider?: "tavily" | "brave" | "exa";
  /** Controls OTEL env forwarding and PI event redaction for workflow phase runs. */
  otel?: OtelConfig;
  telemetry?: {
    workflowName?: string;
    phaseName?: string;
    triggerId?: string;
    workflowRunId?: string;
  };
  /**
   * Absolute host paths to skill directories (each containing SKILL.md
   * plus optional scripts/, references/, assets/). Staged into the
   * sandbox at `<workspace>/.agents/skills/<basename>/` before the agent
   * runs — gondolin via symlink, docker via a per-skill read-only
   * bind-mount — so pi-coding-agent's built-in `.agents/skills/`
   * auto-discovery surfaces them as an XML catalogue in the system
   * prompt. Resolved by `phaseConfigFor` in the workflow runner from
   * the phase's `skill:`/`skills:` field.
   */
  skillPaths?: string[];
}

/**
 * Normalized status of one agentic-pi extension for a single run.
 * Keyed by extension name ("file-search" | "github" | "web-search") in
 * an {@link ExtensionStatusMap}. agentic-pi emits these as `extension_status`
 * events at run start and on `RunResult.{fileSearch,github,webSearch}`;
 * lastlight captures them so the dashboard and logs show which extensions
 * (e.g. FFF file-search) were actually active.
 */
export interface ExtensionStatus {
  /** "configured" when the extension loaded, "skipped" otherwise. */
  status: string;
  /** file-search only: "override" | "tools-only" | "tools-and-ui". */
  mode?: string;
  /** web-search only: the resolved search provider. */
  provider?: string;
  /** Number of tools the extension registered. */
  toolCount?: number;
  /** Why it was skipped (e.g. "no-credentials", "resolve-failed"). */
  reason?: string;
}

export type ExtensionStatusMap = Record<string, ExtensionStatus>;

/**
 * Result from an agent execution.
 */
export interface ExecutionResult {
  success: boolean;
  output: string;
  turns: number;
  error?: string;
  durationMs: number;
  /** Session id captured from the runtime's stream. */
  sessionId?: string;
  /** Total USD cost reported by the runtime. Zero under OAuth/subscription auth. */
  costUsd?: number;
  /** Tokens billed as fresh input (no cache hit). */
  inputTokens?: number;
  /** Tokens that triggered a cache write. */
  cacheCreationInputTokens?: number;
  /** Tokens served from prompt cache (heavily discounted). */
  cacheReadInputTokens?: number;
  /** Output tokens generated by the model. */
  outputTokens?: number;
  /** API-side duration (excludes orchestrator overhead). */
  apiDurationMs?: number;
  /** Mapped stop reason ("success" / "error_*" / etc.). */
  stopReason?: string;
  /**
   * Which agentic-pi extensions were active for this run, keyed by name.
   * Surfaced in the dashboard's phase-detail panel and persisted to the
   * `executions.extension_status` column.
   */
  extensions?: ExtensionStatusMap;
}

export type GitAccessProfile = "read" | "issues-write" | "review-write" | "repo-write";

/**
 * agentic-pi's GitHub extension uses the same four profile names — they
 * pass through unchanged. Kept as an explicit map so renames on either
 * side surface as a type error rather than a silent runtime mismatch.
 */
export const AGENTIC_PROFILE_FOR: Record<GitAccessProfile, string> = {
  read: "read",
  "issues-write": "issues-write",
  "review-write": "review-write",
  "repo-write": "repo-write",
};

export interface GitSandboxAccess {
  owner: string;
  repo: string;
  profile: GitAccessProfile;
  /**
   * When true, sandbox MCP can mint/refresh tokens using the app PEM.
   * Leave false for lower-trust runs to keep private key material inaccessible.
   */
  allowMcpAppAuth?: boolean;
  /**
   * When set, the harness pre-clones the repo at this branch into the
   * task's workspace before the sandbox container starts. The agent then
   * sees the workspace already checked out — no `clone_repo` call needed
   * inside the session. Used by read-only workflows (pr-review, pr-fix)
   * that operate on an existing branch rather than creating one.
   *
   * Build-style workflows that create a new lastlight/* branch from main
   * leave this unset — they start empty and let the agent set up the
   * branch fresh.
   */
  prePopulateBranch?: string;
  /**
   * The owning workflow run id. Stamped into a `<workDir>/.lastlight-run`
   * marker by the pre-clone so a reused per-PR workspace (see
   * `workflowScopedTaskId` for pr-review / pr-fix) can tell "next phase of
   * the same run" (preserve the checkout — build's plan.md lives here) from
   * "a fresh run reusing an old PR dir" (fetch + hard-reset + clean, keeping
   * node_modules warm). Unset for non-workflow callers, which keep the old
   * skip-if-`.git`-exists behaviour.
   */
  runId?: string;
  /**
   * Clone shallowly (`--depth 1 --single-branch`). Set for read-only
   * workflows that never need history; repo-write workflows (build, pr-fix,
   * security-feedback) keep the deeper `--depth 50` clone so rebases / amends
   * have headroom.
   */
  shallow?: boolean;
}

export const GITHUB_PERMISSION_PROFILES: Record<GitAccessProfile, GitHubTokenPermissions> = {
  read: {
    contents: "read",
    issues: "read",
    pull_requests: "read",
    metadata: "read",
  },
  "issues-write": {
    contents: "read",
    issues: "write",
    pull_requests: "read",
    metadata: "read",
  },
  "review-write": {
    contents: "read",
    issues: "write",
    pull_requests: "write",
    metadata: "read",
  },
  "repo-write": {
    contents: "write",
    issues: "write",
    pull_requests: "write",
    metadata: "read",
  },
};

export function loadAgentContext(_dir?: string): string {
  return loadResolvedAgentContext();
}
