import { readFileSync, readdirSync } from "fs";
import { join, resolve } from "path";
import type { GitHubTokenPermissions } from "./git-auth.js";

/**
 * Default directory for agent context files (soul, rules, etc.). Concatenated
 * into AGENTS.md inside the sandbox by the entrypoint; the harness only reads
 * this when assembling a system prompt for non-sandbox paths.
 */
const AGENT_CONTEXT_DIR = resolve("agent-context");

import type { SandboxBackend } from "../config.js";

/**
 * Configuration for an agent execution.
 */
export interface ExecutorConfig {
  /** Working directory for the agent (used by the no-sandbox path). */
  cwd?: string;
  /** Maximum conversation turns. Unused by agentic-pi; kept for API stability. */
  maxTurns?: number;
  /** Model id (e.g. "anthropic/claude-sonnet-4-6"). */
  model?: string;
  /**
   * Pi thinking level: `off | minimal | low | medium | high | xhigh`.
   * Forwarded to agentic-pi as the `thinking` option. When omitted,
   * agentic-pi uses the model's default.
   */
  variant?: string;
  /** Path to agent context directory. */
  agentContextDir?: string;
  /** Directory for persistent state. */
  stateDir?: string;
  /** Directory for agent sandboxes (cloned repos). */
  sandboxDir?: string;
  /** Where the shim writes dashboard envelope jsonl. */
  sessionsDir?: string;
  /** Workflow sandbox backend (overrides config-level default). */
  sandbox?: SandboxBackend;
}

/**
 * Result from an agent execution.
 */
export interface ExecutionResult {
  success: boolean;
  output: string;
  turns: number;
  error?: string;
  durationMs: number;
  /** Session id captured from the runtime's stream. */
  sessionId?: string;
  /** Total USD cost reported by the runtime. Zero under OAuth/subscription auth. */
  costUsd?: number;
  /** Tokens billed as fresh input (no cache hit). */
  inputTokens?: number;
  /** Tokens that triggered a cache write. */
  cacheCreationInputTokens?: number;
  /** Tokens served from prompt cache (heavily discounted). */
  cacheReadInputTokens?: number;
  /** Output tokens generated by the model. */
  outputTokens?: number;
  /** API-side duration (excludes orchestrator overhead). */
  apiDurationMs?: number;
  /** Mapped stop reason ("success" / "error_*" / etc.). */
  stopReason?: string;
}

export type GitAccessProfile = "read" | "issues-write" | "review-write" | "repo-write";

/**
 * agentic-pi's GitHub extension uses the same four profile names — they
 * pass through unchanged. Kept as an explicit map so renames on either
 * side surface as a type error rather than a silent runtime mismatch.
 */
export const AGENTIC_PROFILE_FOR: Record<GitAccessProfile, string> = {
  read: "read",
  "issues-write": "issues-write",
  "review-write": "review-write",
  "repo-write": "repo-write",
};

export interface GitSandboxAccess {
  owner: string;
  repo: string;
  profile: GitAccessProfile;
  /**
   * When true, sandbox MCP can mint/refresh tokens using the app PEM.
   * Leave false for lower-trust runs to keep private key material inaccessible.
   */
  allowMcpAppAuth?: boolean;
  /**
   * When set, the harness pre-clones the repo at this branch into the
   * task's workspace before the sandbox container starts. The agent then
   * sees the workspace already checked out — no `clone_repo` call needed
   * inside the session. Used by read-only workflows (pr-review, pr-fix)
   * that operate on an existing branch rather than creating one.
   *
   * Build-style workflows that create a new lastlight/* branch from main
   * leave this unset — they start empty and let the agent set up the
   * branch fresh.
   */
  prePopulateBranch?: string;
}

export const GITHUB_PERMISSION_PROFILES: Record<GitAccessProfile, GitHubTokenPermissions> = {
  read: {
    contents: "read",
    issues: "read",
    pull_requests: "read",
    metadata: "read",
  },
  "issues-write": {
    contents: "read",
    issues: "write",
    pull_requests: "read",
    metadata: "read",
  },
  "review-write": {
    contents: "read",
    issues: "write",
    pull_requests: "write",
    metadata: "read",
  },
  "repo-write": {
    contents: "write",
    issues: "write",
    pull_requests: "write",
    metadata: "read",
  },
};

/**
 * Load all .md files from the agent-context directory and concatenate them
 * into a single string. The sandbox entrypoint does this independently to
 * produce AGENTS.md; this helper exists for in-process callers.
 */
export function loadAgentContext(dir?: string): string {
  const contextDir = dir || AGENT_CONTEXT_DIR;
  try {
    const files = readdirSync(contextDir)
      .filter((f) => f.endsWith(".md"))
      .sort();
    return files
      .map((f) => readFileSync(join(contextDir, f), "utf-8"))
      .join("\n\n---\n\n");
  } catch {
    console.warn(`[profiles] No agent context found at ${contextDir}`);
    return "";
  }
}
