import type { GitHubTokenPermissions } from "./git-auth.js";
import type { SandboxBackend } from "../config.js";
import { loadAgentContext as loadResolvedAgentContext } from "../workflows/loader.js";

/**
 * Configuration for an agent execution.
 */
export interface ExecutorConfig {
  /** Working directory for the agent (used by the no-sandbox path). */
  cwd?: string;
  /** Maximum conversation turns. Unused by agentic-pi; kept for API stability. */
  maxTurns?: number;
  /** Model id (e.g. "anthropic/claude-sonnet-4-6"). */
  model?: string;
  /**
   * Pi thinking level: `off | minimal | low | medium | high | xhigh`.
   * Forwarded to agentic-pi as the `thinking` option. When omitted,
   * agentic-pi uses the model's default.
   */
  variant?: string;
  /** Path to agent context directory. */
  agentContextDir?: string;
  /** Directory for persistent state. */
  stateDir?: string;
  /** Directory for agent sandboxes (cloned repos). */
  sandboxDir?: string;
  /** Where the shim writes dashboard envelope jsonl. */
  sessionsDir?: string;
  /** Workflow sandbox backend (overrides config-level default). */
  sandbox?: SandboxBackend;
  /**
   * Bypass the HTTP egress allowlist for this phase. When true:
   *   - gondolin: `allowedHttpHosts: ["*"]` is passed to agentic-pi.
   *   - docker:   the sandbox container's HTTPS_PROXY points at the open
   *               tinyproxy sidecar instead of the strict one.
   *
   * Default false. Set via the `unrestricted_egress` field on a workflow
   * phase — used for phases that need broad web access (e.g. an explore
   * phase that searches third-party documentation).
   */
  unrestrictedEgress?: boolean;
  /**
   * Enable agentic-pi's web-search extension (`web_search` / `web_fetch`
   * tools). Default false. agentic-pi auto-enables web search whenever a
   * provider env var (`TAVILY_API_KEY`, `BRAVE_SEARCH_API_KEY`,
   * `EXA_API_KEY`) is present, so we pass an explicit `false` downstream
   * to suppress auto-enable for non-explore workflows.
   */
  webSearch?: boolean;
  /**
   * Force a specific web-search provider. When unset, agentic-pi picks
   * one based on which API key env var is present (Tavily > Exa > Brave).
   */
  webSearchProvider?: "tavily" | "brave" | "exa";
  /**
   * Absolute host paths to skill directories (each containing SKILL.md
   * plus optional scripts/, references/, assets/). Staged into the
   * sandbox at `<workspace>/.agents/skills/<basename>/` before the agent
   * runs — gondolin via symlink, docker via a per-skill read-only
   * bind-mount — so pi-coding-agent's built-in `.agents/skills/`
   * auto-discovery surfaces them as an XML catalogue in the system
   * prompt. Resolved by `phaseConfigFor` in the workflow runner from
   * the phase's `skill:`/`skills:` field.
   */
  skillPaths?: string[];
}

/**
 * Result from an agent execution.
 */
export interface ExecutionResult {
  success: boolean;
  output: string;
  turns: number;
  error?: string;
  durationMs: number;
  /** Session id captured from the runtime's stream. */
  sessionId?: string;
  /** Total USD cost reported by the runtime. Zero under OAuth/subscription auth. */
  costUsd?: number;
  /** Tokens billed as fresh input (no cache hit). */
  inputTokens?: number;
  /** Tokens that triggered a cache write. */
  cacheCreationInputTokens?: number;
  /** Tokens served from prompt cache (heavily discounted). */
  cacheReadInputTokens?: number;
  /** Output tokens generated by the model. */
  outputTokens?: number;
  /** API-side duration (excludes orchestrator overhead). */
  apiDurationMs?: number;
  /** Mapped stop reason ("success" / "error_*" / etc.). */
  stopReason?: string;
}

export type GitAccessProfile = "read" | "issues-write" | "review-write" | "repo-write";

/**
 * agentic-pi's GitHub extension uses the same four profile names — they
 * pass through unchanged. Kept as an explicit map so renames on either
 * side surface as a type error rather than a silent runtime mismatch.
 */
export const AGENTIC_PROFILE_FOR: Record<GitAccessProfile, string> = {
  read: "read",
  "issues-write": "issues-write",
  "review-write": "review-write",
  "repo-write": "repo-write",
};

export interface GitSandboxAccess {
  owner: string;
  repo: string;
  profile: GitAccessProfile;
  /**
   * When true, sandbox MCP can mint/refresh tokens using the app PEM.
   * Leave false for lower-trust runs to keep private key material inaccessible.
   */
  allowMcpAppAuth?: boolean;
  /**
   * When set, the harness pre-clones the repo at this branch into the
   * task's workspace before the sandbox container starts. The agent then
   * sees the workspace already checked out — no `clone_repo` call needed
   * inside the session. Used by read-only workflows (pr-review, pr-fix)
   * that operate on an existing branch rather than creating one.
   *
   * Build-style workflows that create a new lastlight/* branch from main
   * leave this unset — they start empty and let the agent set up the
   * branch fresh.
   */
  prePopulateBranch?: string;
}

export const GITHUB_PERMISSION_PROFILES: Record<GitAccessProfile, GitHubTokenPermissions> = {
  read: {
    contents: "read",
    issues: "read",
    pull_requests: "read",
    metadata: "read",
  },
  "issues-write": {
    contents: "read",
    issues: "write",
    pull_requests: "read",
    metadata: "read",
  },
  "review-write": {
    contents: "read",
    issues: "write",
    pull_requests: "write",
    metadata: "read",
  },
  "repo-write": {
    contents: "write",
    issues: "write",
    pull_requests: "write",
    metadata: "read",
  },
};

export function loadAgentContext(_dir?: string): string {
  return loadResolvedAgentContext();
}
