import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { DEFAULT_ALLOWLIST, isWildcardHost } from "./egress-allowlist.js";

/**
 * Egress firewall config generation for the docker sandbox backend.
 *
 * Architecture (replaces the earlier tinyproxy CONNECT-proxy):
 *
 *   sandbox-egress (internal: true, subnet 172.30.0.0/24)
 *     ├─ sandbox containers              (docker run --dns <coredns-ip>)
 *     ├─ coredns-strict   172.30.0.10    → returns nginx-strict IP for allowlist hosts, NXDOMAIN otherwise
 *     ├─ coredns-open     172.30.0.11    → returns nginx-open IP for ANY hostname (except hard-deny SSRF magnets)
 *     ├─ nginx-egress-strict 172.30.0.20 → ssl_preread, SNI must match allowlist; tunnel upstream via proxy-egress
 *     └─ nginx-egress-open   172.30.0.21 → tunnel any SNI; client DNS already gated through coredns-open
 *
 * Why this instead of a forward proxy (tinyproxy/smokescreen): clients
 * inside the sandbox (especially the OpenAI/Anthropic SDKs that build
 * their own undici dispatchers) don't honour HTTP_PROXY / HTTPS_PROXY.
 * Forcing them to cooperate is a losing battle. By spoofing DNS and
 * peeking SNI at the network layer, the sandbox sees no proxy at all —
 * it dials `api.openai.com:443` directly. The firewall intercepts the
 * connection by virtue of being the only thing the spoofed DNS pointed
 * at.
 *
 * Inspired by Vercel Sandbox's egress firewall (SNI peeking, no env
 * vars). Their implementation also handles TLS termination for
 * credentials brokering and Postgres STARTTLS — we don't (yet).
 *
 * ## Wildcards
 *
 * Entries in egress-allowlist.ts with a leading dot (`".github.com"`)
 * match the apex plus every subdomain. nginx's `map` directive supports
 * this syntax natively. CoreDNS uses the `template` plugin with an
 * anchored regex to do the same.
 */

/** Fixed IPs assigned in docker-compose.yml so `--dns` and nginx upstreams can reference them. */
export const COREDNS_STRICT_IP = "172.30.0.10";
export const COREDNS_OPEN_IP = "172.30.0.11";
export const NGINX_STRICT_IP = "172.30.0.20";
export const NGINX_OPEN_IP = "172.30.0.21";

/** Subnet for sandbox-egress. Compose declares this CIDR so the IPs above are valid. */
export const SANDBOX_EGRESS_SUBNET = "172.30.0.0/24";

/**
 * Hostnames the open coredns explicitly NXDOMAINs even in unrestricted
 * mode — known SSRF magnets. nginx's `ssl_preread` SNI inspection alone
 * can't catch hostnames that resolve to private IPs (the DNS server
 * we control gets the first say), so this is the right layer to enforce
 * "no cloud metadata, no internal services" even with `unrestricted_egress`.
 */
const OPEN_MODE_HARD_DENY: readonly string[] = [
  "metadata.google.internal",
  "169.254.169.254", // GCP / AWS / Azure metadata service IP literal
];

/**
 * Convert one allowlist entry to its nginx `map` line.
 *
 *   "api.openai.com" → 'api.openai.com  api.openai.com:443;'
 *   ".github.com"    → '.github.com     $ssl_preread_server_name:443;'
 *
 * Exact matches force the upstream to the named host (defence in depth: even
 * if the SNI somehow varies, we connect to the canonical host). Wildcards
 * use the original SNI as the upstream — we don't know which subdomain
 * the client asked for at config-gen time.
 */
function nginxMapLine(entry: string): string {
  if (isWildcardHost(entry)) {
    // Leading dot is nginx's own syntax for "this domain and subdomains".
    return `        ${entry} $ssl_preread_server_name:443;`;
  }
  return `        ${entry} ${entry}:443;`;
}

/**
 * Convert one allowlist entry to a CoreDNS `template` block that returns
 * the nginx IP for any matching query.
 */
function corednsTemplateForEntry(entry: string, nginxIp: string): string {
  // CoreDNS sees FQDNs with a trailing dot. The pattern matches both the
  // apex and every subdomain when the entry is wildcarded.
  const bareHost = isWildcardHost(entry) ? entry.slice(1) : entry;
  const escapedHost = bareHost.replaceAll(".", "\\.");
  const pattern = isWildcardHost(entry)
    ? `(^|\\.)${escapedHost}\\.$`
    : `^${escapedHost}\\.$`;
  return `    template IN A {
        match ${pattern}
        answer "{{ .Name }} 60 IN A ${nginxIp}"
    }`;
}

/** Build the strict nginx.conf — ssl_preread + map on SNI allowlist. */
export function renderNginxStrictConf(): string {
  const mapLines = DEFAULT_ALLOWLIST.map(nginxMapLine).join("\n");
  return `# Generated by lastlight at harness boot. DO NOT EDIT BY HAND —
# source of truth is src/sandbox/egress-allowlist.ts.

error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events { worker_connections 1024; }

# Streams (TCP/UDP). \`ssl_preread\` reads the TLS ClientHello without
# terminating the session, exposing the SNI hostname as
# \`$ssl_preread_server_name\`. We \`map\` that to an upstream — anything
# unmatched is sunk to 127.0.0.1:1 (no listener, instant reset).
stream {
  log_format basic '$remote_addr -> $ssl_preread_server_name -> $upstream_addr status=$status';
  access_log /dev/stdout basic;

  # Runtime resolver for upstream hostnames (docker's embedded DNS).
  resolver 127.0.0.11 valid=30s ipv6=off;

  # Allowlist. Leading-dot entries (e.g. ".github.com") match the apex
  # plus any subdomain via nginx's built-in map wildcard syntax.
  map $ssl_preread_server_name $upstream_target {
${mapLines}
    # Anything else → black hole. The connection resets immediately;
    # no data ever leaves the sandbox-egress network.
    default 127.0.0.1:1;
  }

  server {
    listen 443;
    ssl_preread on;
    proxy_pass $upstream_target;
    proxy_connect_timeout 5s;
    proxy_timeout 60s;
  }
}
`;
}

/** Build the open nginx.conf — no SNI allowlist, just tunnel whatever DNS pointed at. */
export function renderNginxOpenConf(): string {
  return `# Generated by lastlight at harness boot. DO NOT EDIT BY HAND.
# This nginx is used only by phases that declared \`unrestricted_egress: true\`.
# No SNI allowlist — every host is tunnelled. The corresponding coredns-open
# refuses to resolve the cloud-metadata hostnames so SSRF to them is blocked
# even in this mode.

error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events { worker_connections 1024; }

stream {
  log_format basic '$remote_addr -> $ssl_preread_server_name -> $upstream_addr status=$status';
  access_log /dev/stdout basic;
  resolver 127.0.0.11 valid=30s ipv6=off;

  server {
    listen 443;
    ssl_preread on;
    # $ssl_preread_server_name is whatever SNI the client sent. Tunnel
    # to that hostname on :443. No allowlist check.
    proxy_pass $ssl_preread_server_name:443;
    proxy_connect_timeout 5s;
    proxy_timeout 60s;
  }
}
`;
}

/** Build the Corefile that returns the strict nginx IP for allowlist hosts. */
export function renderCorefileStrict(): string {
  const templates = DEFAULT_ALLOWLIST.map((entry) =>
    corednsTemplateForEntry(entry, NGINX_STRICT_IP),
  ).join("\n");
  return `# Generated by lastlight from src/sandbox/egress-allowlist.ts.
# For each allowlist entry, a template block returns nginx-egress-strict's
# IP. Queries that don't match any template fall through to the catch-all
# NXDOMAIN at the end.
.:53 {
${templates}
    # Catch-all: NXDOMAIN for anything not explicitly allowed.
    template IN ANY {
        rcode NXDOMAIN
    }
    errors
    log
}
`;
}

/** Build the Corefile that returns the open nginx IP for ANY hostname (except hard-denies). */
export function renderCorefileOpen(): string {
  const denyPatterns = OPEN_MODE_HARD_DENY.map((host) => {
    const escaped = host.replaceAll(".", "\\.");
    return `        match (^|\\.)${escaped}\\.$`;
  }).join("\n");
  return `# Generated by lastlight. Used by sandbox phases with unrestricted_egress: true.
# Returns nginx-egress-open's IP for every hostname EXCEPT the SSRF hard-denies
# (cloud metadata literals etc).
.:53 {
    # Hard-deny patterns first — NXDOMAIN regardless of mode.
    template IN ANY {
${denyPatterns}
        rcode NXDOMAIN
    }
    # Everything else → nginx-egress-open IP.
    template IN A {
        answer "{{ .Name }} 60 IN A ${NGINX_OPEN_IP}"
    }
    # AAAA returns empty (we route only via IPv4).
    template IN AAAA {
        rcode NOERROR
    }
    errors
    log
}
`;
}

/**
 * Write the four config files under $STATE_DIR/proxy/. Idempotent.
 * Returns the directory path. Compose bind-mounts this dir into the
 * coredns + nginx containers read-only.
 */
export function writeEgressFirewallConfigs(stateDir: string): string {
  const dir = join(stateDir, "proxy");
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "nginx-strict.conf"), renderNginxStrictConf());
  writeFileSync(join(dir, "nginx-open.conf"), renderNginxOpenConf());
  writeFileSync(join(dir, "Corefile.strict"), renderCorefileStrict());
  writeFileSync(join(dir, "Corefile.open"), renderCorefileOpen());
  return dir;
}
