import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { DEFAULT_ALLOWLIST } from "./egress-allowlist.js";

/**
 * Tinyproxy config generation for the docker sandbox backend.
 *
 * The harness writes four files to `$STATE_DIR/proxy/` at boot:
 *   - `strict.conf`       — destination allowlist mode.
 *   - `open.conf`         — no destination allowlist; optional private-IP
 *                           destination denylist (see private-IP toggle).
 *   - `filter-strict.txt` — host patterns the strict proxy will allow.
 *   - `filter-open.txt`   — host patterns the open proxy will deny when
 *                           the private-IP floor is enabled.
 *
 * Both confs are bind-mounted into the `tinyproxy-strict` and
 * `tinyproxy-open` services declared in `docker-compose.yml`. A sandbox
 * container's `HTTPS_PROXY` env var picks one based on the phase's
 * `unrestricted_egress` flag.
 *
 * Tinyproxy filters HTTPS by inspecting the destination of the client's
 * `CONNECT` request — no TLS interception. That's sufficient for the
 * "stop exfil to attacker-controlled hosts" threat we care about, plus
 * the metadata-service literals (`169.254.169.254`, `metadata.google.internal`)
 * that an SSRF probe would aim at.
 *
 * Limitation: tinyproxy matches the literal CONNECT host *before* DNS
 * resolution. A hostname like `evil.example.com` that resolves to a
 * private IP would not be caught by these patterns. Catching that
 * requires a resolve-then-check proxy (Envoy with `dns_resolver`, or a
 * custom Go proxy). The current setup raises the bar against the
 * common case (curl-to-metadata-IP-literal) but is not a complete
 * post-resolve defense — track follow-up if we need that.
 */

const PROXY_PORT = 8888;

/**
 * Destination host patterns rejected when `LASTLIGHT_BLOCK_PRIVATE_IPS`
 * is enabled. Anchored regex against the CONNECT host string.
 *
 * Each entry is a POSIX extended regex (we set `FilterExtended Yes`).
 * Matching is case-insensitive (`FilterCaseSensitive No`). Patterns
 * target IP *literals* in the CONNECT target — hostnames that resolve
 * to private IPs at the DNS layer slip past this filter (see file
 * docstring above).
 */
const PRIVATE_DESTINATION_PATTERNS: readonly string[] = [
  // RFC1918 — 10.0.0.0/8
  String.raw`^10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$`,
  // RFC1918 — 172.16.0.0/12
  String.raw`^172\.(1[6-9]|2[0-9]|3[01])\.[0-9]{1,3}\.[0-9]{1,3}$`,
  // RFC1918 — 192.168.0.0/16
  String.raw`^192\.168\.[0-9]{1,3}\.[0-9]{1,3}$`,
  // Loopback — 127.0.0.0/8
  String.raw`^127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$`,
  // Link-local — 169.254.0.0/16 (covers AWS/GCP/Azure metadata 169.254.169.254)
  String.raw`^169\.254\.[0-9]{1,3}\.[0-9]{1,3}$`,
  // IPv6 loopback ::1 (bare or bracketed)
  String.raw`^\[?::1\]?$`,
  // IPv6 link-local fe80::/10
  String.raw`^\[?fe[89ab][0-9a-f]:`,
  // IPv6 ULA fc00::/7
  String.raw`^\[?f[cd][0-9a-f]{2}:`,
  // GCP metadata service shortcut hostnames
  String.raw`^metadata$`,
  String.raw`^metadata\.google\.internal$`,
];

export interface TinyproxyConfigOptions {
  /**
   * When true, `open.conf` emits a destination denylist that rejects
   * private/loopback/link-local IP literals and the well-known cloud
   * metadata hostnames. (`strict.conf` blocks them inherently — anything
   * not in its allowlist is denied.)
   *
   * Default: read from `LASTLIGHT_BLOCK_PRIVATE_IPS` env var; treats
   * anything other than `0`/`false`/`no` as enabled. Defaults to enabled
   * if the env var is unset.
   */
  blockPrivateIps?: boolean;
}

function privateIpBlockEnabled(): boolean {
  const raw = (process.env.LASTLIGHT_BLOCK_PRIVATE_IPS ?? "").toLowerCase().trim();
  if (raw === "") return true;
  return !(raw === "0" || raw === "false" || raw === "no");
}

/** Build the contents of the strict tinyproxy.conf. */
export function renderStrictConf(_opts: TinyproxyConfigOptions = {}): string {
  // Note: the `blockPrivateIps` toggle has no effect on strict.conf —
  // FilterDefaultDeny + the allowlist make private destinations
  // unreachable regardless. We accept the option for signature symmetry
  // with renderOpenConf and to document the design choice.
  return [
    "# Generated by lastlight at harness boot. DO NOT EDIT BY HAND —",
    "# the source of truth is src/sandbox/egress-allowlist.ts.",
    "",
    `Port ${PROXY_PORT}`,
    "Listen 0.0.0.0",
    "Timeout 600",
    "DefaultErrorFile \"/usr/share/tinyproxy/default.html\"",
    "StatHost \"tinyproxy.stats\"",
    "LogLevel Info",
    "MaxClients 100",
    "",
    "# Anyone on the docker network can use this proxy. The docker network",
    "# itself is `internal: true`, so this is not an open relay.",
    "Allow 0.0.0.0/0",
    "",
    "# HTTPS CONNECT — restricted to 443 so the agent can't tunnel to",
    "# arbitrary services on allowlisted hosts.",
    "ConnectPort 443",
    "",
    "# Destination allowlist. FilterDefaultDeny + the allowlist mean any",
    "# CONNECT target that isn't in filter-strict.txt is rejected with",
    "# a 403 — including private IP literals and metadata hostnames,",
    "# which would never be in the allowlist anyway.",
    "FilterDefaultDeny Yes",
    "FilterCaseSensitive No",
    "FilterExtended Yes",
    "FilterURLs Off",
    `Filter "${proxyFilterPath("filter-strict.txt")}"`,
    "",
  ].join("\n");
}

/** Build the contents of the open tinyproxy.conf. */
export function renderOpenConf(opts: TinyproxyConfigOptions = {}): string {
  const blockPrivate = opts.blockPrivateIps ?? privateIpBlockEnabled();
  const lines = [
    "# Generated by lastlight at harness boot. DO NOT EDIT BY HAND.",
    "# This proxy is used only by phases that declared",
    "# `unrestricted_egress: true`. No destination allowlist — any host",
    "# is reachable except those caught by the private-IP destination",
    "# denylist below (when enabled).",
    "",
    `Port ${PROXY_PORT}`,
    "Listen 0.0.0.0",
    "Timeout 600",
    "DefaultErrorFile \"/usr/share/tinyproxy/default.html\"",
    "StatHost \"tinyproxy.stats\"",
    "LogLevel Info",
    "MaxClients 100",
    "",
    "Allow 0.0.0.0/0",
    "",
    "ConnectPort 443",
    "",
  ];
  if (blockPrivate) {
    lines.push(
      "# Destination denylist for SSRF protection. FilterDefaultDeny=No",
      "# means everything is allowed by default; entries in filter-open.txt",
      "# are the *denied* exceptions (private IP literals + metadata hosts).",
      "# Toggle off via LASTLIGHT_BLOCK_PRIVATE_IPS=0 — the Filter directive",
      "# and filter file are then both omitted.",
      "FilterDefaultDeny No",
      "FilterCaseSensitive No",
      "FilterExtended Yes",
      "FilterURLs Off",
      `Filter "${proxyFilterPath("filter-open.txt")}"`,
      "",
    );
  } else {
    lines.push(
      "# Private-IP blocking disabled (LASTLIGHT_BLOCK_PRIVATE_IPS=0).",
      "# Every destination is reachable — use with care.",
      "",
    );
  }
  return lines.join("\n");
}

/** Build the strict-mode allowlist filter file (one regex per allowed host). */
export function renderStrictFilterList(): string {
  const lines = [
    "# Generated by lastlight from src/sandbox/egress-allowlist.ts.",
    "# Edit the TypeScript source, not this file.",
    "# Used by strict.conf in FilterDefaultDeny=Yes mode — each entry is",
    "# an ALLOWED host pattern.",
    "",
  ];
  for (const host of DEFAULT_ALLOWLIST) {
    // Escape literal dots; allow the host on its own or as a subdomain
    // suffix (e.g. raw.githubusercontent.com still matches when the agent
    // hits a path under it).
    const escaped = host.replaceAll(".", "\\.");
    lines.push(`(^|\\.)${escaped}$`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Build the open-mode denylist filter file (private IPs + metadata hosts). */
export function renderOpenFilterList(): string {
  return [
    "# Generated by lastlight from src/sandbox/tinyproxy-config.ts.",
    "# Used by open.conf in FilterDefaultDeny=No mode — each entry is",
    "# a DENIED host pattern. Matched against the CONNECT target (literal,",
    "# pre-DNS-resolution).",
    "",
    ...PRIVATE_DESTINATION_PATTERNS,
    "",
  ].join("\n");
}

function proxyFilterPath(filename: string): string {
  // Path inside the tinyproxy container — matches the agent-data volume
  // mount declared in docker-compose.yml. The harness writes filter files
  // alongside the confs at $STATE_DIR/proxy/, which the proxies see at
  // /app/data/proxy/ inside their containers.
  return `/app/data/proxy/${filename}`;
}

/**
 * Write strict.conf, open.conf, filter-strict.txt, and filter-open.txt
 * under $STATE_DIR/proxy/. Idempotent — safe to call on every boot.
 * Returns the directory path so docker-compose / SIGHUP wiring can find
 * the files.
 */
export function writeProxyConfigs(stateDir: string, opts: TinyproxyConfigOptions = {}): string {
  const proxyDir = join(stateDir, "proxy");
  mkdirSync(proxyDir, { recursive: true });
  writeFileSync(join(proxyDir, "strict.conf"), renderStrictConf(opts));
  writeFileSync(join(proxyDir, "open.conf"), renderOpenConf(opts));
  writeFileSync(join(proxyDir, "filter-strict.txt"), renderStrictFilterList());
  writeFileSync(join(proxyDir, "filter-open.txt"), renderOpenFilterList());
  return proxyDir;
}

export const TINYPROXY_PORT = PROXY_PORT;
export const TINYPROXY_PRIVATE_DESTINATION_PATTERNS = PRIVATE_DESTINATION_PATTERNS;
