/**
 * Scorecard rendering + SWE-bench-compatible artifacts.
 *
 *  - A stdout table comparing models on resolved% / triage-correct% / tokens /
 *    cost / latency.
 *  - `scorecard.json`  — the structured roll-up.
 *  - `predictions.jsonl` — SWE-bench predictions shape
 *    (`{ instance_id, model_name_or_path, model_patch }`), so the same artifact
 *    is consumable by SWE-bench's own harness.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { InstanceResult } from "./schema.js";
import { fLabel } from "./grade.js";

/** A case still running / queued (live runs only — surfaced in the dashboard). */
export interface PendingCase {
  tier: string;
  model: string;
  instance_id: string;
  status: "running" | "pending";
  /** For a running case: the archived session jsonl path (live-updated during
   * the run), so the dashboard can open + follow the transcript as it streams. */
  sessionLog?: string;
}

/**
 * Run-level metadata persisted into `scorecard.json` so the dashboard can label,
 * order, and live-poll runs without re-deriving from the current config.
 */
export interface RunMeta {
  runId: string;
  generatedAt: string;
  tiers: string[];
  /**
   * The comparison axis for this run. `"models"` (default) compares N models,
   * each forced across every workflow step. `"config"` compares N deployment
   * configs (per-step model maps merged from an overlay's `config.yaml`) — the
   * setup you actually ship. Absent ⇒ `"models"` (back-compat with older runs).
   */
  runType?: "models" | "config";
  /** Axis labels under test (model ids in `models` runs, config/overlay names
   * in `config` runs) — what the scorecard table displays as rows. */
  models: string[];
  /** Trials per case (`--runs N`). */
  runs: number;
  /** Short git SHA of the code/workflows under test, when in a repo. */
  gitSha?: string;
  /** Display labels keyed by model id (so the dashboard reads them off disk). */
  labels?: Record<string, string>;
  /** While the run is in flight: the dashboard polls + shows a "live" badge.
   * Absent/false on the final write so the published scorecard is static. */
  live?: boolean;
  /** Progress text for the live badge (e.g. "7/30"). */
  progress?: string;
  /** Cases not yet finished (live runs): shown as running/queued rows. */
  pending?: PendingCase[];
  /** PID of the process writing this scorecard — liveness check for `clean`. */
  pid?: number;
  /** ISO timestamp refreshed by the run's heartbeat ticker while in flight. A
   * `live` run whose heartbeat is stale (or absent — i.e. an older orphaned run)
   * was killed/crashed: the index treats it as {@link RunMeta.interrupted}. */
  heartbeat?: string;
  /** Set when a run was finalized as killed/crashed (by `clean`, or derived at
   * read time from a stale heartbeat). Distinguishes it from a clean finish. */
  interrupted?: boolean;
  /** pr-review only: where this run's model(s) would rank among Martian's Code
   * Review Bench tools, scored over EXACTLY the PRs this run covered (subset-fair).
   * Absent when the tier ships no `martian-leaderboard.json` sidecar or nothing
   * graded. {@link computeMartianRanking}. */
  martian?: MartianRanking;
}

/** One Martian tool's tp/fp/fn on one PR, from the shipped sidecar. */
export interface MartianToolMetric {
  tp: number;
  fp: number;
  fn: number;
}

/**
 * The shipped `datasets/pr-review/martian-leaderboard.json` — Martian's per-tool,
 * per-PR tp/fp/fn (one judge model), keyed by OUR `instance_id`, so a run can be
 * ranked against Martian's tools with no external checkout. Generated by
 * `scripts/gen-martian-leaderboard.ts`.
 */
export interface MartianSidecar {
  judgeModel: string;
  toolDisplayNames: Record<string, string>;
  instances: Record<string, { url: string; toolMetrics: Record<string, MartianToolMetric> }>;
}

/** A tool's (or our model's) micro-aggregated score over the covered PR subset. */
export interface MartianScore {
  /** Tool key (e.g. `"gemini"`) or the model arm label for our own row. */
  key: string;
  /** Display name (Martian's for tools; the model label for ours). */
  name: string;
  tp: number;
  fp: number;
  fn: number;
  precision: number;
  recall: number;
  f1: number;
}

/** Our model's placement among the tools over the covered subset. */
export interface MartianModelRank extends MartianScore {
  /** 1-based rank once this model is slotted into the sorted tool list. */
  rank: number;
  /** Total ranked entries (tools that cover every PR + 1 for this model). */
  of: number;
}

/**
 * "Where would we rank?" — Martian's tools and our model(s), each micro-scored
 * over the SAME covered PRs. Subset-fair by construction; cross-judge (our reviews
 * are graded by our judge, Martian's tools by `judgeModel`) — the UI says so.
 */
export interface MartianRanking {
  judgeModel: string;
  /** Covered PRs = graded instances that exist in the sidecar. */
  prCount: number;
  coveredInstances: string[];
  /** Martian tools that cover every one of the `prCount` PRs, sorted desc by F1. */
  tools: MartianScore[];
  /** Our arm(s), each with its rank among `tools`. */
  models: MartianModelRank[];
}

/** A live run's heartbeat must be refreshed within this window to count as
 * genuinely running; beyond it the writer is presumed dead. Comfortably larger
 * than the run loop's 20s heartbeat ticker. */
export const HEARTBEAT_STALE_MS = 90_000;

/** True if a heartbeat timestamp is recent enough that the writer is presumed
 * alive. Absent/unparseable ⇒ not fresh (older orphaned runs have no heartbeat). */
export function heartbeatFresh(heartbeat: string | undefined, nowMs: number): boolean {
  if (!heartbeat) return false;
  const t = Date.parse(heartbeat);
  return Number.isFinite(t) && nowMs - t <= HEARTBEAT_STALE_MS;
}

export interface Scorecard {
  models: ModelSummary[];
  results: InstanceResult[];
  /** Present on the final, on-disk scorecard; absent on live in-flight writes. */
  meta?: RunMeta;
}

export interface ModelSummary {
  model: string;
  total: number;
  codeFixResolved: number;
  codeFixTotal: number;
  behavioralOk: number;
  behavioralTotal: number;
  /** PR-review tier: N cases graded by the judge + mean precision/recall/F-beta. */
  reviewTotal: number;
  avgPrecision: number;
  avgRecall: number;
  avgFbeta: number;
  /** The β the graded cases used (F1 by default). Undefined when nothing graded. */
  reviewBeta?: number;
  avgInputTokens: number;
  avgCachedTokens: number;
  avgOutputTokens: number;
  totalCostUsd: number;
  p50DurationMs: number;
  errors: number;
}

/**
 * Fold N trials of ONE case (same model + instance) into a single result:
 *   - binary verdicts (behavioral / resolved) are WORST-case — true only if
 *     every non-errored trial passed (a reliability measure), with the pass
 *     count kept alongside for variance.
 *   - cost / tokens / latency are the MEAN across non-errored trials.
 * A single trial is returned unchanged. If every trial errored, the aggregate
 * carries that error.
 */
export function aggregateTrials(trials: InstanceResult[]): InstanceResult {
  if (trials.length === 1) return trials[0];
  const base = trials[0];
  const ok = trials.filter((t) => !t.error);
  if (!ok.length) {
    return { ...base, trials: 0, trialErrors: trials.length, error: base.error ?? "all trials errored" };
  }

  const mean = (xs: number[]) => (xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0);
  const out: InstanceResult = {
    ...base,
    error: undefined,
    inputTokens: Math.round(mean(ok.map((t) => t.inputTokens))),
    cachedTokens: Math.round(mean(ok.map((t) => t.cachedTokens))),
    outputTokens: Math.round(mean(ok.map((t) => t.outputTokens))),
    costUsd: mean(ok.map((t) => t.costUsd)),
    durationMs: Math.round(mean(ok.map((t) => t.durationMs))),
    githubMutations: Math.round(mean(ok.map((t) => t.githubMutations ?? 0))),
    trials: ok.length,
    trialErrors: trials.length - ok.length,
    // Worst-case (matches resolved/behavioral): marked blocked only if every
    // non-errored trial was a deliberate gate block.
    blocked: ok.every((t) => t.blocked) || undefined,
  };

  // behavioral: worst-case ok, checks AND'd by name, keep a failing detail.
  if (ok.some((t) => t.behavioral)) {
    const passes = ok.filter((t) => t.behavioral?.ok).length;
    const names = [...new Set(ok.flatMap((t) => t.behavioral?.checks.map((c) => c.name) ?? []))];
    const checks = names.map((name) => {
      const perTrial = ok.map((t) => t.behavioral?.checks.find((c) => c.name === name));
      const failing = perTrial.find((c) => c && !c.ok);
      return { name, ok: perTrial.every((c) => c?.ok), detail: failing?.detail };
    });
    out.behavioral = { ok: passes === ok.length, checks };
    out.behavioralPass = passes;
  }

  // resolved: worst-case; keep a failing trial's test breakdown + a patch.
  if (ok.some((t) => t.resolved !== undefined)) {
    const passes = ok.filter((t) => t.resolved).length;
    const rep = ok.find((t) => !t.resolved) ?? ok[0];
    out.resolved = passes === ok.length;
    out.resolvedPass = passes;
    out.failToPass = rep.failToPass;
    out.passToPass = rep.passToPass;
    out.executionLog = rep.executionLog; // log of the same trial the breakdown came from
    out.model_patch = (ok.find((t) => t.resolved) ?? ok[0]).model_patch;
  }

  // review (pr-review): mean the metrics across non-errored trials; carry a
  // representative trial's FP/FN lists (the worst — lowest F-beta — for inspection).
  const rev = ok.filter((t) => t.review);
  if (rev.length) {
    const rep = [...rev].sort((a, b) => (a.review!.fbeta - b.review!.fbeta))[0];
    out.review = {
      precision: mean(rev.map((t) => t.review!.precision)),
      recall: mean(rev.map((t) => t.review!.recall)),
      fbeta: mean(rev.map((t) => t.review!.fbeta)),
      beta: rev[0].review!.beta,
      posted: Math.round(mean(rev.map((t) => t.review!.posted))),
      gold: rev[0].review!.gold,
      matched: Math.round(mean(rev.map((t) => t.review!.matched))),
      falsePositives: rep.review!.falsePositives,
      falseNegatives: rep.review!.falseNegatives,
      trace: rep.review!.trace,
    };
    out.reviewTrials = rev.length;
  }

  return out;
}

/** Per-model aggregation over a set of results (one tier or all of them). */
export function summarizeModels(results: InstanceResult[]): ModelSummary[] {
  const byModel = new Map<string, InstanceResult[]>();
  for (const r of results) {
    const list = byModel.get(r.model) ?? [];
    list.push(r);
    byModel.set(r.model, list);
  }

  const models: ModelSummary[] = [];
  for (const [model, list] of byModel) {
    const codeFix = list.filter((r) => r.resolved !== undefined);
    const behavioral = list.filter((r) => r.behavioral !== undefined && !r.error);
    const review = list.filter((r) => r.review !== undefined && !r.error);
    const durations = list.map((r) => r.durationMs).sort((a, b) => a - b);
    models.push({
      model,
      total: list.length,
      codeFixResolved: codeFix.filter((r) => r.resolved).length,
      codeFixTotal: codeFix.length,
      behavioralOk: behavioral.filter((r) => r.behavioral?.ok).length,
      behavioralTotal: behavioral.length,
      reviewTotal: review.length,
      avgPrecision: avg(review.map((r) => r.review!.precision)),
      avgRecall: avg(review.map((r) => r.review!.recall)),
      avgFbeta: avg(review.map((r) => r.review!.fbeta)),
      reviewBeta: review[0]?.review!.beta,
      avgInputTokens: avg(list.map((r) => r.inputTokens)),
      avgCachedTokens: avg(list.map((r) => r.cachedTokens)),
      avgOutputTokens: avg(list.map((r) => r.outputTokens)),
      totalCostUsd: list.reduce((s, r) => s + r.costUsd, 0),
      p50DurationMs: durations[Math.floor(durations.length / 2)] ?? 0,
      errors: list.filter((r) => r.error).length,
    });
  }
  return models;
}

export function summarize(results: InstanceResult[]): Scorecard {
  return { models: summarizeModels(results), results };
}

/** Load a tier's Martian leaderboard sidecar, or undefined if it ships none. */
export function loadMartianSidecar(tierRoot: string): MartianSidecar | undefined {
  const path = join(tierRoot, "martian-leaderboard.json");
  if (!existsSync(path)) return undefined;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as MartianSidecar;
  } catch {
    return undefined; // a malformed sidecar just hides the panel, never breaks a run
  }
}

const f1Of = (tp: number, fp: number, fn: number) => {
  const p = tp + fp ? tp / (tp + fp) : 0;
  const r = tp + fn ? tp / (tp + fn) : 0;
  return { precision: p, recall: r, f1: p + r ? (2 * p * r) / (p + r) : 0 };
};

/**
 * Rank this run's model(s) against Martian's Code Review Bench tools over EXACTLY
 * the PRs the run covered (subset-fair). For each covered PR we have Martian's
 * per-tool tp/fp/fn (from the sidecar) and our own (matched / posted-matched /
 * gold-matched from the judge). Everything is micro-aggregated — summed then
 * P/R/F1 — matching Martian's own `overall_metrics`. A tool is ranked only if it
 * has data on EVERY covered PR, so every row is scored on the identical PR set.
 * Returns undefined when nothing graded overlaps the sidecar (⇒ no panel).
 */
export function computeMartianRanking(
  results: InstanceResult[],
  sidecar: MartianSidecar,
): MartianRanking | undefined {
  // Covered PRs: graded (has a review) AND present in the sidecar. Dedup because a
  // multi-model run repeats each instance_id once per model.
  const covered = [...new Set(results.filter((r) => r.review && sidecar.instances[r.instance_id]).map((r) => r.instance_id))].sort();
  if (!covered.length) return undefined;

  // Martian tools that appear on EVERY covered PR — only those are comparable on
  // the identical subset. Micro-aggregate each across the covered PRs.
  const onAll = covered
    .map((id) => new Set(Object.keys(sidecar.instances[id].toolMetrics)))
    .reduce((acc, s) => new Set([...acc].filter((t) => s.has(t))));
  const tools: MartianScore[] = [...onAll]
    .map((key) => {
      let tp = 0, fp = 0, fn = 0;
      for (const id of covered) {
        const m = sidecar.instances[id].toolMetrics[key];
        tp += m.tp; fp += m.fp; fn += m.fn;
      }
      return { key, name: sidecar.toolDisplayNames[key] ?? key, tp, fp, fn, ...f1Of(tp, fp, fn) };
    })
    .sort((a, b) => b.f1 - a.f1);

  // Our arm(s): micro-aggregate the judge's matched/posted/gold over the covered
  // PRs the arm actually graded, then slot into the tool ranking by F1.
  const byModel = new Map<string, InstanceResult[]>();
  for (const r of results) {
    if (r.review && sidecar.instances[r.instance_id]) (byModel.get(r.model) ?? byModel.set(r.model, []).get(r.model)!).push(r);
  }
  const models: MartianModelRank[] = [...byModel.entries()]
    .map(([key, list]) => {
      let tp = 0, fp = 0, fn = 0;
      for (const r of list) {
        const rev = r.review!;
        tp += rev.matched;
        fp += Math.max(0, rev.posted - rev.matched);
        fn += Math.max(0, rev.gold - rev.matched);
      }
      const score = f1Of(tp, fp, fn);
      // Rank = 1 + (tools strictly better). `of` counts the tool field plus us.
      const rank = 1 + tools.filter((t) => t.f1 > score.f1).length;
      return { key, name: key, tp, fp, fn, ...score, rank, of: tools.length + 1 };
    })
    .sort((a, b) => b.f1 - a.f1);

  return { judgeModel: sidecar.judgeModel, prCount: covered.length, coveredInstances: covered, tools, models };
}

export function renderTable(card: Scorecard, labels: Record<string, string> = {}): string {
  // Show the pr-review columns (prec/rec/F-beta) only when some run graded a
  // review — otherwise keep the table lean for triage/code-fix. The F-beta column
  // is labelled by the β the run used (F1 by default).
  const hasReview = card.models.some((m) => m.reviewTotal > 0);
  const fCol = fLabel(card.models.find((m) => m.reviewBeta !== undefined)?.reviewBeta ?? 1);
  const header = [
    "model",
    "code-fix",
    "behavioral",
    ...(hasReview ? ["prec", "rec", fCol] : []),
    "in tok",
    "cached",
    "out tok",
    "cost $",
    "p50",
    "err",
  ];
  const rows = card.models.map((m) => [
    labels[m.model] ?? m.model,
    m.codeFixTotal ? `${m.codeFixResolved}/${m.codeFixTotal}` : "—",
    m.behavioralTotal ? `${m.behavioralOk}/${m.behavioralTotal}` : "—",
    ...(hasReview
      ? [
          m.reviewTotal ? m.avgPrecision.toFixed(2) : "—",
          m.reviewTotal ? m.avgRecall.toFixed(2) : "—",
          m.reviewTotal ? m.avgFbeta.toFixed(2) : "—",
        ]
      : []),
    fmtTokens(m.avgInputTokens),
    fmtTokens(m.avgCachedTokens),
    fmtTokens(m.avgOutputTokens),
    m.totalCostUsd.toFixed(4),
    fmtMs(m.p50DurationMs),
    String(m.errors),
  ]);
  return table([header, ...rows]);
}

/**
 * Write `scorecard.json` atomically (temp-file + rename) so a dashboard polling
 * the file during a live run never reads a half-written JSON. Used both for the
 * incremental live writes and the final static write.
 */
export function writeScorecard(dir: string, card: Scorecard): string {
  mkdirSync(dir, { recursive: true });
  const file = join(dir, "scorecard.json");
  const tmp = join(dir, ".scorecard.json.tmp");
  // Drop the heavy inline `model_patch` from the serialized scorecard — it's
  // polled live every 1.5s and the diff can be large. predictions.jsonl keeps
  // it (built from the in-memory card), and the dashboard reads the diff from
  // each result's `modelPatchFile` (the discrete changes.diff artifact).
  writeFileSync(tmp, JSON.stringify(card, (k, v) => (k === "model_patch" ? undefined : v), 2));
  renameSync(tmp, file);
  return file;
}

export function writeArtifacts(dir: string, card: Scorecard): void {
  writeScorecard(dir, card);
  const preds = card.results
    .filter((r) => r.model_patch !== undefined)
    .map((r) => JSON.stringify({ instance_id: r.instance_id, model_name_or_path: r.model, model_patch: r.model_patch ?? "" }))
    .join("\n");
  writeFileSync(join(dir, "predictions.jsonl"), preds ? preds + "\n" : "");
}

// ── dashboard index (filesystem → JSON the SPA fetches) ───────────────────────

/** Per-tier model roll-up — a run can span several tiers (`triage+code-fix`),
 * and the overview trends each tier separately, so the index breaks the summary
 * down per tier rather than aggregating across them. */
export interface TierSummary {
  tier: string;
  models: ModelSummary[];
}

/** One run as the dashboard index sees it: identity + per-tier roll-up + the
 * relative URL of its full `scorecard.json` (fetched lazily for the detail view). */
export interface IndexRun {
  /** URL-safe token used in the SPA route (the run subdir name, or "root" for a
   * legacy flat-layout run written directly into the tier dir). */
  id: string;
  /** Relative URL of this run's scorecard.json, served under `/data/`. */
  scorecard: string;
  runId: string;
  generatedAt: string;
  gitSha?: string;
  /** Comparison axis (see {@link RunMeta.runType}) — lets the SPA badge a run
   * without fetching its scorecard. Absent ⇒ `"models"`. */
  runType?: "models" | "config";
  tiers: string[];
  /** Display labels keyed by model id, carried for the SPA. */
  labels: Record<string, string>;
  /** Per-tier model roll-up (enough for the overview tables; the detail view
   * fetches the full scorecard for per-instance rows). */
  byTier: TierSummary[];
  /** Trials per case (`--runs N`). */
  runs: number;
  /** True while the run is still writing (the SPA keeps polling it). Derived:
   * the scorecard's `live` flag AND a fresh heartbeat. */
  live: boolean;
  /** The run was `live` but its writer died (stale/absent heartbeat) or it was
   * finalized as interrupted by `clean` — shown as "interrupted", not running. */
  interrupted: boolean;
  /** Progress text for the live badge (e.g. "7/30"). */
  progress?: string;
  /** Live-run case counts (so the overview can show "running" vs "queued"
   * instead of a bare "live" for a tier whose cases haven't started). */
  running?: number;
  queued?: number;
}

/** One tier-combo directory (`eval-results/<key>`) and its runs, newest first. */
export interface IndexTier {
  key: string;
  runs: IndexRun[];
}

export interface DashboardIndex {
  generatedAt: string;
  tiers: IndexTier[];
}

/** Map a parsed scorecard into an {@link IndexRun}. `dir` is the run subdir name
 * ("" for a legacy flat-layout run sitting directly in the tier dir). */
function indexRun(tierKey: string, dir: string, card: Scorecard, nowMs: number): IndexRun {
  const meta = card.meta;
  // A run only counts as live if its heartbeat is fresh; a `live` scorecard with
  // a stale/absent heartbeat (writer killed or crashed) is an interrupted run.
  const fresh = heartbeatFresh(meta?.heartbeat, nowMs);
  const isLive = !!meta?.live && fresh;
  const isInterrupted = !!meta?.interrupted || (!!meta?.live && !fresh);
  const id = dir || "root";
  const data = dir ? `${dir}/scorecard.json` : "scorecard.json";
  const results = card.results ?? [];

  // Group results by their own tier (a run can span several), preserving
  // first-seen order; fall back to the run's first declared tier / the dir key.
  const fallbackTier = meta?.tiers?.[0] ?? tierKey;
  const tierOrder: string[] = [];
  const byTierResults = new Map<string, InstanceResult[]>();
  for (const r of results) {
    const t = r.tier ?? fallbackTier;
    if (!byTierResults.has(t)) {
      byTierResults.set(t, []);
      tierOrder.push(t);
    }
    byTierResults.get(t)!.push(r);
  }
  const byTier: TierSummary[] = tierOrder.map((tier) => ({
    tier,
    models: summarizeModels(byTierResults.get(tier)!),
  }));

  return {
    id,
    scorecard: `/data/${encodeURIComponent(tierKey)}/${data}`,
    runId: meta?.runId ?? dir ?? tierKey,
    generatedAt: meta?.generatedAt ?? dir ?? "",
    gitSha: meta?.gitSha,
    runType: meta?.runType,
    tiers: meta?.tiers ?? tierOrder,
    labels: meta?.labels ?? {},
    byTier,
    runs: meta?.runs ?? 1,
    live: isLive,
    interrupted: isInterrupted,
    progress: meta?.progress,
    // No running/queued cases once interrupted — the writer is gone.
    running: isInterrupted ? 0 : (meta?.pending ?? []).filter((p) => p.status === "running").length,
    queued: isInterrupted ? 0 : (meta?.pending ?? []).filter((p) => p.status === "pending").length,
  };
}

const parseCard = (file: string): Scorecard | null => {
  try {
    return JSON.parse(readFileSync(file, "utf8")) as Scorecard;
  } catch {
    return null; // half-written or malformed — skip rather than abort the index
  }
};

/** Scan one tier-combo dir for runs (subdir-per-run, plus a legacy flat run if a
 * scorecard sits directly in the dir), newest first. */
export function indexTier(resultsRoot: string, key: string, nowMs: number = Date.now()): IndexRun[] {
  const tierDir = join(resultsRoot, key);
  if (!existsSync(tierDir)) return [];
  const runs: IndexRun[] = [];
  for (const ent of readdirSync(tierDir, { withFileTypes: true })) {
    if (!ent.isDirectory()) continue;
    const card = parseCard(join(tierDir, ent.name, "scorecard.json"));
    if (card) runs.push(indexRun(key, ent.name, card, nowMs));
  }
  const flat = parseCard(join(tierDir, "scorecard.json"));
  if (flat) runs.push(indexRun(key, "", flat, nowMs));
  const sortKey = (r: IndexRun) => r.generatedAt || r.runId;
  return runs.sort((a, b) => (sortKey(a) < sortKey(b) ? 1 : sortKey(a) > sortKey(b) ? -1 : 0));
}

/**
 * Build the whole dashboard index from `eval-results/` on disk: one entry per
 * tier-combo dir (those holding at least one run), each with its runs newest
 * first. The server recomputes this per request, so accumulating runs and live
 * in-flight writes show up without any manifest file to keep in sync.
 */
export function buildIndex(resultsRoot: string, generatedAt: string): DashboardIndex {
  if (!existsSync(resultsRoot)) return { generatedAt, tiers: [] };
  const nowMs = Date.parse(generatedAt) || Date.now();
  const tiers: IndexTier[] = [];
  for (const ent of readdirSync(resultsRoot, { withFileTypes: true })) {
    if (!ent.isDirectory()) continue;
    const runs = indexTier(resultsRoot, ent.name, nowMs);
    if (runs.length) tiers.push({ key: ent.name, runs });
  }
  // Tier-combos with the most recent activity first.
  tiers.sort((a, b) => {
    const ka = a.runs[0]?.generatedAt ?? "";
    const kb = b.runs[0]?.generatedAt ?? "";
    return ka < kb ? 1 : ka > kb ? -1 : 0;
  });
  return { generatedAt, tiers };
}

// ── helpers ─────────────────────────────────────────────────────────────────

function avg(xs: number[]): number {
  return xs.length ? xs.reduce((a, b) => a + b, 0) / xs.length : 0;
}
/** Compact token count: <1000 verbatim, else "k" (one decimal under 10k).
 * Tolerates undefined/NaN (e.g. a scorecard.json predating cached-token
 * tracking) → "0". */
export function fmtTokens(n: number): string {
  const v = Number.isFinite(n) ? n : 0;
  if (v < 1000) return String(Math.round(v));
  const k = v / 1000;
  return `${k >= 10 ? Math.round(k) : k.toFixed(1)}k`;
}
function fmtMs(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const s = Math.round(ms / 1000);
  return s < 60 ? `${s}s` : `${Math.floor(s / 60)}m${String(s % 60).padStart(2, "0")}`;
}
function table(rows: string[][]): string {
  const widths = rows[0].map((_, i) => Math.max(...rows.map((r) => (r[i] ?? "").length)));
  return rows
    .map((r) => r.map((c, i) => (c ?? "").padEnd(widths[i])).join("  "))
    .join("\n");
}
