#!/usr/bin/env node
/**
 * Last Light setup wizard — `npx lastlight setup`
 *
 * Guides a user from a bare server to a fully configured Last Light instance.
 * Uses @clack/prompts for the interactive UI and chalk for styling.
 */

import { randomBytes } from "node:crypto";
import {
  existsSync,
  readFileSync,
  readdirSync,
  writeFileSync,
  mkdirSync,
  chmodSync,
  copyFileSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { execSync } from "node:child_process";
import * as p from "@clack/prompts";
import chalk from "chalk";

// ── Brand colors ───────────────────────────────────────────────────────────

const gold = chalk.hex("#F0B429");
const teal = chalk.hex("#1A7A8A");
const orange = chalk.hex("#E8752A");
const dim = chalk.dim;
const bright = chalk.white.bold;

// ── Types ───────────────────────────────────────────────────────────────────

export interface SetupConfig {
  GITHUB_APP_ID: string;
  GITHUB_APP_INSTALLATION_ID: string;
  WEBHOOK_SECRET: string;
  ADMIN_SECRET: string;
  DOMAIN: string;
  /** Model id consumed by agentic-pi / pi-ai, e.g. "anthropic/claude-sonnet-4-6" or "openai/gpt-5.5". */
  LASTLIGHT_MODEL: string;
  /** Set when the chosen model uses an OpenAI-prefixed provider. */
  OPENAI_API_KEY?: string;
  /** Set when the chosen model uses an Anthropic-prefixed provider. */
  ANTHROPIC_API_KEY?: string;
  /** Set when the chosen model uses an OpenRouter-prefixed provider. */
  OPENROUTER_API_KEY?: string;
  ADMIN_PASSWORD?: string;
  SLACK_BOT_TOKEN?: string;
  SLACK_APP_TOKEN?: string;
  SLACK_DELIVERY_CHANNEL?: string;
  SLACK_ALLOWED_USERS?: string;
  useCaddy: boolean;
  pemSourcePath: string;
}

// ── Validation helpers (exported for unit tests) ────────────────────────────

export function isPositiveInt(s: string): boolean {
  return /^\d+$/.test(s) && parseInt(s, 10) > 0;
}

/**
 * Try to resolve a PEM path. Checks: as given, relative to cwd, relative
 * to parent dir (for when the wizard chdir'd into a clone), and with ~ expanded.
 * Returns the resolved absolute path or null if not found.
 */
function resolvePem(input: string): string | null {
  let expanded = input;
  if (expanded.startsWith("~/")) {
    expanded = join(process.env.HOME || "", expanded.slice(2));
  }
  const candidates = [
    resolve(expanded),
    resolve("..", expanded),
  ];
  for (const candidate of candidates) {
    if (isPemFile(candidate)) return candidate;
  }
  return null;
}

export function isPemFile(filePath: string): boolean {
  try {
    const content = readFileSync(filePath, "utf8");
    return (
      content.startsWith("-----BEGIN RSA PRIVATE KEY-----") ||
      content.startsWith("-----BEGIN PRIVATE KEY-----")
    );
  } catch {
    return false;
  }
}

export function isAnthropicKey(s: string): boolean {
  return s.startsWith("sk-ant-");
}

export function isOpenaiKey(s: string): boolean {
  return s.startsWith("sk-") && !s.startsWith("sk-ant-") && !s.startsWith("sk-or-");
}

export function isOpenrouterKey(s: string): boolean {
  return s.startsWith("sk-or-");
}

/**
 * Default model — kept aligned with `config.ts`'s `DEFAULT_MODEL`.
 * Update both in lockstep when the canonical default changes.
 */
export const DEFAULT_LASTLIGHT_MODEL = "anthropic/claude-sonnet-4-6";

export function isSlackBotToken(s: string): boolean {
  return s.startsWith("xoxb-");
}

export function isSlackAppToken(s: string): boolean {
  return s.startsWith("xapp-");
}

// ── .env serialization (exported for unit tests) ────────────────────────────

export function buildEnvContent(config: SetupConfig): string {
  const lines: string[] = [
    "# ── Last Light — Environment Variables ─────────────────────",
    "# Generated by: npx lastlight setup",
    "",
    "# ── GitHub App (required) ────────────────────────────────",
    `GITHUB_APP_ID=${config.GITHUB_APP_ID}`,
    `GITHUB_APP_PRIVATE_KEY_PATH=./secrets/app.pem`,
    `GITHUB_APP_INSTALLATION_ID=${config.GITHUB_APP_INSTALLATION_ID}`,
    "",
    "# ── Webhook (required) ──────────────────────────────────",
    `WEBHOOK_SECRET=${config.WEBHOOK_SECRET}`,
    "",
    "# ── Domain (used by Caddy for TLS) ─────────────────────────────────────",
    `DOMAIN=${config.DOMAIN}`,
    "",
    "# ── Model + provider API key ────────────────────────────────",
    `LASTLIGHT_MODEL=${config.LASTLIGHT_MODEL}`,
    "# Set whichever matches your LASTLIGHT_MODEL (anthropic/…, openai/…, or openrouter/…).",
  ];
  if (config.OPENAI_API_KEY) {
    lines.push(`OPENAI_API_KEY=${config.OPENAI_API_KEY}`);
  }
  if (config.ANTHROPIC_API_KEY) {
    lines.push(`ANTHROPIC_API_KEY=${config.ANTHROPIC_API_KEY}`);
  }
  if (config.OPENROUTER_API_KEY) {
    lines.push(`OPENROUTER_API_KEY=${config.OPENROUTER_API_KEY}`);
  }
  lines.push(
    "",
    "# ── Admin Dashboard ────────────────────────────────────────",
    `ADMIN_SECRET=${config.ADMIN_SECRET}`,
  );

  if (config.ADMIN_PASSWORD) {
    lines.push(`ADMIN_PASSWORD=${config.ADMIN_PASSWORD}`);
  }

  if (config.SLACK_BOT_TOKEN) {
    lines.push("");
    lines.push("# ── Slack ──────────────────────────────────────────────────");
    lines.push(`SLACK_BOT_TOKEN=${config.SLACK_BOT_TOKEN}`);
    if (config.SLACK_APP_TOKEN) {
      lines.push(`SLACK_APP_TOKEN=${config.SLACK_APP_TOKEN}`);
    }
    if (config.SLACK_DELIVERY_CHANNEL) {
      lines.push(`SLACK_DELIVERY_CHANNEL=${config.SLACK_DELIVERY_CHANNEL}`);
    }
    if (config.SLACK_ALLOWED_USERS) {
      lines.push(`SLACK_ALLOWED_USERS=${config.SLACK_ALLOWED_USERS}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

// ── Clack helper — bail on cancel ───────────────────────────────────────────

function required<T>(value: T | symbol): T {
  if (p.isCancel(value)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }
  return value;
}

// ── Banner ──────────────────────────────────────────────────────────────────

function printBanner(): void {
  // Inner width = 46 chars between the box-drawing borders
  const W = 46;
  const pad = (text: string, styled: string) => {
    const left = Math.floor((W - text.length) / 2);
    const right = W - text.length - left;
    return gold("  │") + " ".repeat(left) + styled + " ".repeat(right) + gold("│");
  };
  const empty = gold("  │") + " ".repeat(W) + gold("│");
  const rule = "─".repeat(W);

  console.log();
  console.log(gold(`  ╭${rule}╮`));
  console.log(empty);
  console.log(pad("✦  L A S T   L I G H T  ✦", bright("✦  L A S T   L I G H T  ✦")));
  console.log(empty);
  console.log(pad("GitHub Repository Maintenance Agent", dim("GitHub Repository Maintenance Agent")));
  console.log(empty);
  console.log(gold(`  ╰${rule}╯`));
  console.log();
}

// ── Preflight ───────────────────────────────────────────────────────────────

function preflight(): void {
  if (!existsSync("docker-compose.yml")) {
    if (existsSync("lastlight/docker-compose.yml")) {
      p.log.info("Found existing lastlight/ directory — continuing setup there.");
      process.chdir("lastlight");
    } else {
      const s = p.spinner();
      s.start("Cloning cliftonc/lastlight ...");
      try {
        execSync("git clone https://github.com/cliftonc/lastlight.git lastlight", {
          stdio: "pipe",
        });
        s.stop("Repository cloned.");
      } catch {
        s.stop("Clone failed.");
        p.log.error("Failed to clone. Please clone manually:");
        p.log.info("  git clone https://github.com/cliftonc/lastlight.git");
        process.exit(1);
      }
      process.chdir("lastlight");
      p.log.info(`Working directory: ${dim(process.cwd())}`);
    }
  }

  try {
    execSync("docker info", { stdio: "ignore" });
  } catch {
    p.log.error("Docker is not running or not installed.");
    p.log.info("Please start Docker and re-run: " + teal("npx lastlight setup"));
    process.exit(1);
  }

  if (existsSync(".env")) {
    p.log.error(".env already exists. To reconfigure, remove it first: " + dim("rm .env"));
    process.exit(1);
  }
}

// ── Setup steps ─────────────────────────────────────────────────────────────

async function collectGitHubApp(): Promise<{
  appId: string;
  installationId: string;
  pemSourcePath: string;
}> {
  p.log.step(gold("GitHub App"));
  p.log.info(
    dim("Create one at ") +
    teal("https://github.com/settings/apps/new") +
    dim(" if you haven't already.")
  );

  const appId = required(
    await p.text({
      message: "GitHub App ID",
      placeholder: "123456",
      validate: (v) =>
        v && isPositiveInt(v) ? undefined : "Must be a positive integer.",
    }),
  );

  const installationId = required(
    await p.text({
      message: "Installation ID",
      placeholder: "789012",
      validate: (v) =>
        v && isPositiveInt(v) ? undefined : "Must be a positive integer.",
    }),
  );

  // Search cwd and parent for .pem files to offer as choices
  const pemCandidates: string[] = [];
  for (const dir of [process.cwd(), resolve("..")]) {
    try {
      for (const f of readdirSync(dir)) {
        if (f.endsWith(".pem")) {
          const full = join(dir, f);
          if (isPemFile(full)) pemCandidates.push(full);
        }
      }
    } catch { /* unreadable dir */ }
  }

  let pemResolved: string;
  if (pemCandidates.length > 0) {
    const choice = required(
      await p.select({
        message: "Private key (.pem)",
        options: [
          ...pemCandidates.map((f) => ({ value: f, label: f.replace(process.env.HOME || "", "~") })),
          { value: "__other__", label: dim("Enter a different path...") },
        ],
      }),
    ) as string;

    if (choice === "__other__") {
      const manual = required(
        await p.text({
          message: "Path to private key (.pem)",
          validate: (v) => {
            if (!v) return "Enter a file path.";
            return resolvePem(v) ? undefined : "File not found or not a valid PEM.";
          },
        }),
      );
      pemResolved = resolvePem(manual as string)!;
    } else {
      pemResolved = choice;
    }
  } else {
    const manual = required(
      await p.text({
        message: "Path to private key (.pem)",
        placeholder: "~/downloads/your-app.private-key.pem",
        validate: (v) => {
          if (!v) return "Enter a file path.";
          return resolvePem(v) ? undefined : "File not found or not a valid PEM.";
        },
      }),
    );
    pemResolved = resolvePem(manual as string)!;
  }

  return {
    appId: appId as string,
    installationId: installationId as string,
    pemSourcePath: pemResolved,
  };
}

async function collectDomain(): Promise<{ domain: string; useCaddy: boolean }> {
  p.log.step(gold("Domain & TLS"));

  const domain = required(
    await p.text({
      message: "Your domain",
      placeholder: "lastlight.example.com",
      validate: (v) =>
        v && v.length > 0 && v.includes(".")
          ? undefined
          : "Enter a valid domain name.",
    }),
  );

  const useCaddy = required(
    await p.confirm({
      message: "Use Caddy for automatic TLS?",
      initialValue: true,
    }),
  );

  p.log.info(`Webhook URL: ${teal(`https://${domain}/webhook`)}`);

  return { domain: domain as string, useCaddy: useCaddy as boolean };
}

async function collectModelAndKey(): Promise<{
  model: string;
  openaiKey?: string;
  anthropicKey?: string;
  openrouterKey?: string;
}> {
  p.log.step(gold("Model provider"));
  p.log.info(
    dim("agentic-pi (pi-ai) is provider-agnostic. Pick the model you want the agent to use; ") +
    dim("the wizard will ask for the matching API key."),
  );

  // Curated short list — extend as new defaults emerge. The custom escape
  // hatch below lets the user enter any provider/model string pi-ai accepts.
  const catalog = [
    DEFAULT_LASTLIGHT_MODEL,
    "anthropic/claude-sonnet-4-6-20251015",
    "openai/gpt-5.5",
    "openrouter/google/gemini-2.5-pro",
    "openrouter/anthropic/claude-sonnet-4.5",
  ];
  // Deduplicate while preserving order (DEFAULT_LASTLIGHT_MODEL first).
  const seen = new Set<string>();
  const ordered: string[] = [];
  for (const m of catalog) {
    if (!seen.has(m)) { seen.add(m); ordered.push(m); }
  }

  const choice = required(
    await p.select({
      message: `LASTLIGHT_MODEL ${dim("(short list — pick 'other' for a custom value)")}`,
      initialValue: DEFAULT_LASTLIGHT_MODEL,
      options: [
        ...ordered.map((m) => ({
          value: m,
          label: m === DEFAULT_LASTLIGHT_MODEL ? `${m} ${dim("(default)")}` : m,
        })),
        { value: "__custom__", label: dim("Enter a different provider/model...") },
      ],
    }),
  ) as string;

  let model = choice;
  if (choice === "__custom__") {
    model = required(
      await p.text({
        message: "provider/model",
        placeholder: "openai/gpt-5.3-codex or anthropic/claude-…",
        validate: (v) =>
          v && /^[a-z][\w-]*\/[A-Za-z][\w.-]+$/.test(v)
            ? undefined
            : "Format must be provider/model (e.g. openai/gpt-5.3-codex).",
      }),
    ) as string;
  }

  const provider = model.split("/")[0].toLowerCase();
  if (provider === "anthropic") {
    const key = required(
      await p.text({
        message: "ANTHROPIC_API_KEY",
        placeholder: "sk-ant-...",
        validate: (v) =>
          v && isAnthropicKey(v) ? undefined : "Must start with sk-ant-",
      }),
    ) as string;
    return { model, anthropicKey: key };
  }
  if (provider === "openai") {
    const key = required(
      await p.text({
        message: "OPENAI_API_KEY",
        placeholder: "sk-...",
        validate: (v) =>
          v && isOpenaiKey(v) ? undefined : "Must start with sk- (and not sk-ant- or sk-or-)",
      }),
    ) as string;
    return { model, openaiKey: key };
  }
  if (provider === "openrouter") {
    const key = required(
      await p.text({
        message: "OPENROUTER_API_KEY",
        placeholder: "sk-or-v1-...",
        validate: (v) =>
          v && isOpenrouterKey(v) ? undefined : "Must start with sk-or-",
      }),
    ) as string;
    return { model, openrouterKey: key };
  }
  // Unknown provider — prompt for any key and route by shape.
  p.log.warn(`Provider "${provider}" isn't auto-detected. Enter the API key your model needs.`);
  const key = required(
    await p.text({
      message: "API key",
      validate: (v) => (v && v.length > 0 ? undefined : "Enter a non-empty key."),
    }),
  ) as string;
  if (isAnthropicKey(key)) return { model, anthropicKey: key };
  if (isOpenrouterKey(key)) return { model, openrouterKey: key };
  return { model, openaiKey: key };
}

async function collectAdminPassword(): Promise<string | undefined> {
  p.log.step(gold("Admin Dashboard"));

  const wantPassword = required(
    await p.confirm({
      message: "Set an admin dashboard password?",
      initialValue: false,
    }),
  );
  if (!wantPassword) return undefined;

  const password = required(
    await p.password({
      message: "Admin password",
      validate: (v) =>
        v && v.length >= 8 ? undefined : "Must be at least 8 characters.",
    }),
  );

  return password as string;
}

async function collectSlack(): Promise<{
  botToken?: string;
  appToken?: string;
  deliveryChannel?: string;
  allowedUsers?: string;
}> {
  p.log.step(gold("Slack") + dim(" (optional)"));

  const wantSlack = required(
    await p.confirm({
      message: "Enable Slack integration?",
      initialValue: false,
    }),
  );
  if (!wantSlack) return {};

  const botToken = required(
    await p.text({
      message: "SLACK_BOT_TOKEN",
      placeholder: "xoxb-...",
      validate: (v) =>
        v && isSlackBotToken(v) ? undefined : "Must start with xoxb-",
    }),
  ) as string;

  const appToken = required(
    await p.text({
      message: "SLACK_APP_TOKEN",
      placeholder: "xapp-...",
      validate: (v) =>
        v && isSlackAppToken(v) ? undefined : "Must start with xapp-",
    }),
  ) as string;

  const deliveryChannel = required(
    await p.text({
      message: "Delivery channel ID",
      placeholder: "C0123456789 (press Enter to skip)",
      defaultValue: "",
    }),
  ) as string;

  const allowedUsers = required(
    await p.text({
      message: "Allowed user IDs",
      placeholder: "U0123,U0456 (press Enter to skip)",
      defaultValue: "",
    }),
  ) as string;

  return {
    botToken,
    appToken,
    deliveryChannel: deliveryChannel || undefined,
    allowedUsers: allowedUsers || undefined,
  };
}

function writeConfig(config: SetupConfig): void {
  p.log.step(gold("Writing config"));

  try {
    mkdirSync("secrets", { recursive: true });
  } catch (err: unknown) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === "EACCES") {
      p.log.error("Permission denied creating secrets/ directory.");
      process.exit(1);
    }
    throw err;
  }

  copyFileSync(config.pemSourcePath, join("secrets", "app.pem"));
  chmodSync(join("secrets", "app.pem"), 0o600);

  const envContent = buildEnvContent(config);
  writeFileSync(".env", envContent, { encoding: "utf8" });
  chmodSync(".env", 0o600);

  p.log.success(
    dim("secrets/app.pem") + " copied " + dim("(mode 600)") + "\n" +
    "  " + dim(".env") + " written " + dim("(mode 600)")
  );
}

/** Detect whether to use `docker compose` (v2) or `docker-compose` (v1/colima). */
function composeCmd(): string {
  try {
    execSync("docker compose version", { stdio: "ignore" });
    return "docker compose";
  } catch {
    try {
      execSync("docker-compose version", { stdio: "ignore" });
      return "docker-compose";
    } catch {
      return "docker compose"; // fall through — will error with a clear message
    }
  }
}

async function dockerBuildAndLaunch(): Promise<void> {
  p.log.step(gold("Docker"));
  const dc = composeCmd();
  p.log.info(dim(`Using: ${dc}`));

  const wantLaunch = required(
    await p.confirm({
      message: "Build and launch Last Light now?",
      initialValue: true,
    }),
  );

  if (!wantLaunch) {
    p.log.info("When ready, run:\n" +
      dim(`  ${dc} --profile build-only build sandbox\n`) +
      dim(`  ${dc} up -d`));
    return;
  }

  const s = p.spinner();

  s.start("Building sandbox image...");
  try {
    execSync(`${dc} --profile build-only build sandbox`, {
      stdio: "pipe",
    });
    s.stop("Sandbox image built.");
  } catch {
    s.stop("Sandbox build failed.");
    p.log.error("Check Docker Compose v2 is installed.");
    process.exit(1);
  }

  s.start("Starting services...");
  try {
    execSync(`${dc} up -d`, { stdio: "pipe" });
    s.stop("Services started.");
  } catch {
    s.stop("Failed to start services.");
    p.log.error("Check docker compose logs for details.");
    process.exit(1);
  }
}

function printSummary(domain: string, webhookSecret: string): void {
  console.log();
  console.log(gold("  ┌──────────────────────────────────────────────┐"));
  console.log(gold("  │") + bright("  Setup complete!                              ") + gold("│"));
  console.log(gold("  └──────────────────────────────────────────────┘"));
  console.log();
  console.log("  " + dim("Webhook URL   ") + teal(`https://${domain}/webhook`));
  console.log("  " + dim("Dashboard     ") + teal(`https://${domain}/admin`));
  console.log();
  console.log("  " + orange("Paste this WEBHOOK_SECRET into your GitHub App settings:"));
  console.log("  " + bright(webhookSecret));
  console.log();
  console.log("  " + dim("Next steps:"));
  console.log("  " + dim("  • Edit agent-context/rules.md to customise bot behaviour"));
  console.log("  " + dim("  • Verify webhook delivery in GitHub App settings"));
  console.log("  " + dim("  • Check logs: ") + teal("docker compose logs -f") + dim(" (or docker-compose)"));
  console.log();
}

// ── Main entry point ─────────────────────────────────────────────────────────

export async function runSetup(): Promise<void> {
  if (!process.stdin.isTTY) {
    console.error("Error: setup must be run interactively (stdin must be a TTY).");
    process.exit(1);
  }

  printBanner();

  p.intro(dim("This wizard will configure Last Light on your server."));

  preflight();

  const { appId, installationId, pemSourcePath } = await collectGitHubApp();
  const webhookSecret = randomBytes(32).toString("hex");
  const adminSecret = randomBytes(32).toString("hex");
  p.log.success("Secrets auto-generated " + dim("(WEBHOOK_SECRET + ADMIN_SECRET)"));

  const { domain, useCaddy } = await collectDomain();
  const { model, openaiKey, anthropicKey, openrouterKey } = await collectModelAndKey();
  const adminPassword = await collectAdminPassword();
  const { botToken, appToken, deliveryChannel, allowedUsers } = await collectSlack();

  const config: SetupConfig = {
    GITHUB_APP_ID: appId,
    GITHUB_APP_INSTALLATION_ID: installationId,
    WEBHOOK_SECRET: webhookSecret,
    ADMIN_SECRET: adminSecret,
    DOMAIN: domain,
    LASTLIGHT_MODEL: model,
    OPENAI_API_KEY: openaiKey,
    ANTHROPIC_API_KEY: anthropicKey,
    OPENROUTER_API_KEY: openrouterKey,
    ADMIN_PASSWORD: adminPassword,
    SLACK_BOT_TOKEN: botToken,
    SLACK_APP_TOKEN: appToken,
    SLACK_DELIVERY_CHANNEL: deliveryChannel,
    SLACK_ALLOWED_USERS: allowedUsers,
    useCaddy,
    pemSourcePath,
  };

  writeConfig(config);
  await dockerBuildAndLaunch();

  p.outro(gold("Last Light is ready."));
  printSummary(domain, webhookSecret);
}
